### ISSUE TITLE
Add Algorithms 

### ISSUE THREAD

**Issue by Lakhankumawat** [Lakhankumawat/LearnCPP#1]
**Add new algorithms , Newcomers are always welcomed with their ideas.**
Do like to contribute and make it a helpful repository for beginners in **CPP**

**Comment by puneetkaur2929** [comment]
hey @Lakhankumawat 
Is this issue still open ? if yes , I wish to contribute.

**Comment by Lakhankumawat** [comment]
Yes @puneetkaur2929  this issue is opened for all and always , you can go ahead and contribute .

**Comment by Meaha7** [comment]
Hi,
I wish to contribute for the hacktoberfest.

**Comment by aditya-gaikwad** [comment]
I want to contribute, kindly add me to this issue.

**Comment by Lakhankumawat** [comment]
> I want to contribute, kindly add me to this issue.

@aditya-gaikwad  there are multiple algorithms you can select one of your choice raise an issue  and start contributing .

1. Take an algorithm which is not present in repo , create a issue - one of maintainer will review it soon .
2. Create a pull request .

Happy Coding !!

**Comment by aditya-gaikwad** [comment]
If my issue contains a problem of leetcode, will it be fine?

**Comment by Lakhankumawat** [comment]
@aditya-gaikwad  Yeah it is fine . But there should be understandable and clearly written code with problem statement link.

**Comment by ujjwalban** [comment]
Can we still contribute?

**Comment by Lakhankumawat** [comment]
> Can we still contribute?

yes you can

**Comment by ujjwalban** [comment]
> > Can we still contribute?
> 
> yes you can

bhaiya i am not able to create branch

**Comment by ujjwalban** [comment]
> > Can we still contribute?
> 
> yes you can

I have created an issue for new algorithm

**Comment by samitkapoor** [comment]
@Lakhankumawat  Can we still contribute?

**Comment by Lakhankumawat** [comment]
yaa sure !

**Comment by samitkapoor** [comment]
@Lakhankumawat Okay then, ill contribute to this in my free time. Thanks!

**Comment by Lakhankumawat** [comment]
no mention at all

**Comment by ishika1501** [comment]
@Lakhankumawat  could you tell me like if we contribute a new algo here , will it be counted or we have to wait for 1st march for contribution ?

**Comment by Lakhankumawat** [comment]
<div align="center">
<img height="350" src="https://user-images.githubusercontent.com/55774240/155681587-9178825d-8868-407e-bea7-ae4497cdab5a.jpg" />
<h3> Tuesday ko aa haina , 1st March ko mast naha dhoke aa okay </h3>
</div>

**Comment by Pragatii08** [comment]
I would like to contribute. Please assign.

**Comment by n4i9kita** [comment]
@Pragatii08 make sure to read the earlier conversations in any issue. Your problem has been answered. https://github.com/Lakhankumawat/LearnCPP/issues/1#issuecomment-932104336

**Comment by uhini0201** [comment]
Hi, I am a contributor of GSSOC'22. Is this issue open?? Can i contribute after 1st march???

**Comment by deepu0201** [comment]
If this issue is still open can i contribute being a part of GSSOC'22. Can you assign this to me??

**Comment by Lakhankumawat** [comment]
Don't worry guys you'll able to contribute , join the meet tomorrow most of the details will be shared there , meeting details are present in READmE

**Comment by rakeshchirla** [comment]
I am a GSSoC'22 participant and would like to work on this task. Can you assign this to me?

**Comment by Lakhankumawat** [comment]
Create an issue for the algorithm you want to add .

**Comment by LakshayN** [comment]
@Lakhankumawat  Hi, I would like to contribute for algorithm to find the maximum area of histogram using stacks.

**Comment by Yash-Parsana** [comment]
hello @Lakhankumawat i would like to add merge sort for linked list

**Comment by Yash-Parsana** [comment]
hello @Lakhankumawat i would like to add Rabin-Karp Algorithm for Pattern Searching

**Comment by wvaibhava** [comment]
I would like to contribute!
