### ISSUE TITLE
Shift Characters

### ISSUE THREAD

**Issue by KayserMasr** [Lakhankumawat/LearnCPP#1006]
### Description

Shift every char the user input by 3 #1006

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Abdulrahman1890** [comment]
please assign me this task @Lucifer4255 @KayserMasr @eltociear @ujjwalban @Hend123
