### ISSUE TITLE
Implementation of Stack using array 

### ISSUE THREAD

**Issue by varsha080** [Lakhankumawat/LearnCPP#102]
### Description

I want to add the code of implementation of stack using array for better understanding of these concept. I will be using C++ for the code. Also, I'm a GSS0C22 contributor. Kindly assign the task to me.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
Kindly update your issue to only one problem, Stack and Queue belong to different folders and can be considered as different PR's kindly work on either Stack or Queue

**Comment by varsha080** [comment]
> Kindly update your issue to only one problem, Stack and Queue belong to different folders and can be considered as different PR's kindly work on either Stack or Queue

I have updated the issue. Kindly assign the task to me!

**Comment by KhushiRana2003** [comment]
I ahve already done this problem plz assign this to me i want to work on this issue an i am also a gssoc participant
