### ISSUE TITLE
Hash table 

### ISSUE THREAD

**Issue by mohanadtalat91** [Lakhankumawat/LearnCPP#1029]
### Description

Add Hash table data structure & it's hash functions in Cpp. 

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by deepan773399** [comment]
I want to work on this issue . Please assign it to me .
