### ISSUE TITLE
Sparse array 

### ISSUE THREAD

**Issue by mohanadtalat91** [Lakhankumawat/LearnCPP#1030]
### Description

Add sparse array using singly linked list data structure. 

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Hend123** [comment]
@mohanadtalat91
Please assign this issue to me
