### ISSUE TITLE
Vector Implementation 

### ISSUE THREAD

**Issue by mohanadtalat91** [Lakhankumawat/LearnCPP#1031]
### Description

I'll implement dynamic array (vector) and it's functionalities only using basic of Cpp. 

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by harshit078** [comment]
Hi @mohanadtalat91, can you assign me this task?

**Comment by hazemtarekelaswad** [comment]
Hey, I am ready to implement this class, could you assign it to me?
