### ISSUE TITLE
First and last occurrence of an element in an array

### ISSUE THREAD

**Issue by Akriti-007** [Lakhankumawat/LearnCPP#1037]
### Description

I am GSSoC 2022 contributor. I would like to add a program that finds the first and last occurrence of an element in an array, which has duplicate inputs.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Hend123** [comment]
Please assign this issue to me @Akriti-007
