### ISSUE TITLE
Merge K sorted linked lists

### ISSUE THREAD

**Issue by Rahul5430** [Lakhankumawat/LearnCPP#105]
### Description

Given K sorted linked lists of size N each, merge them and print the sorted output.

Please assign this to me. I am participating in GSSOC'22.
I will provide a proper description of the code with time and space complexity and test cases.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Smriti123Shukla** [comment]
I have worked previously on these types of questions. Kindly, assign me this task. I am a participant in Gssoc'22.
