### ISSUE TITLE
Want to add Dijkstra Algorithm

### ISSUE THREAD

**Issue by maheshdbabar9340** [Lakhankumawat/LearnCPP#1073]
### Description

Dijkstra Algorithm using the priority queue
 

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

I would like to add Dijkstras algorithm using Priority Queue, Please assign this to me. Thank You.

**Comment by harshit078** [comment]
Hi @maheshdbabar9340, I would like to solve this issue, can you assign this to me?

**Comment by maheshdbabar9340** [comment]
@Mrjoy832 I added dijkstras algorithm cpp code please let me know if any changes are required. 

Waiting for your response. Thank You.

**Comment by Mrjoy832** [comment]
Will be checked by eve

**Comment by maheshdbabar9340** [comment]
@Mrjoy832 Will you please check again pull request #1135? I just changed now.
