### ISSUE TITLE
Map/Unordered_Map in STL 

### ISSUE THREAD

**Issue by Akshat-z** [Lakhankumawat/LearnCPP#1080]
### Description

I want to add the map and unordered_map inside the S-STL/C-Containers folder.

### Domain

Standard Template Library

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by deepan773399** [comment]
I want to work on this issue . Please assign it to me .
