### ISSUE TITLE
Binary Tree Operations

### ISSUE THREAD

**Issue by AnIkeT126** [Lakhankumawat/LearnCPP#1082]
### Description

C++ program to perform the following functions on Binary Tree:
Insertion at a random node
Deletion at a random node
Finding the height of a tree
Finding a parent node

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by harshit078** [comment]
Hi, can you assign this to me?

**Comment by NamanKothari5** [comment]
I m willing to work on this!
Please assign this to me

**Comment by Sakshi-209** [comment]
/ assign this to me.
