### ISSUE TITLE
Create Possible path between 2 vertices

### ISSUE THREAD

**Issue by AnIkeT126** [Lakhankumawat/LearnCPP#1083]
### Description

Create Possible path between 2 vertices in CPP

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by deepan773399** [comment]
I want to work on this issue . Please assign it to me .
