### ISSUE TITLE
Trapping Rain Water Problem

### ISSUE THREAD

**Issue by shubhamlakheraa** [Lakhankumawat/LearnCPP#110]
### Description

Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after raining.

The problem statement will be solved under Problem Statement & Solutions folder.

I will provide a proper description of the code with time and space complexity.

Participation through GSSOC'22.

Can I work on this?

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by shubhamlakheraa** [comment]
@Lakhankumawat

**Comment by miraj0507** [comment]
Have you gone through the contributing guidelines?

**Comment by shubhamlakheraa** [comment]
Yes.

**Comment by shubhamlakheraa** [comment]
Yes I have gone through the contributing guidelines.

**Comment by shubhamlakheraa** [comment]
Yes, I have gone through the contributing guidelines.
