### ISSUE TITLE
Remove Nth node from end of the linked list 

### ISSUE THREAD

**Issue by DlVYANSH** [Lakhankumawat/LearnCPP#111]
### Description

Head of the linked list will be given, our program will remove nth node from end of the linked list and display the list.

I am a contributor in gssoc'22. Please assign this to me
I will provide optimal code with description, time and space complexity and comments plus test cases.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Poojaamangal** [comment]
please have look at this @iamgunjan

**Comment by rutika1823** [comment]
Please, Can you assign this to me @Lakhankumawat
