### ISSUE TITLE
Hi I would like to get started with contributing to this repo as a part of GSSoC ' 22

### ISSUE THREAD

**Issue by sauradip007** [Lakhankumawat/LearnCPP#112]
### Description

I have practiced questions on data structures like hashmaps , priority queues, tries and DP. I would like to add those files into the repo for the same.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
Hey are you a part of Gssoc 22, kindly raise an issue reading the guidelines
