### ISSUE TITLE
Insert and Delete a node in Singly Linked List

### ISSUE THREAD

**Issue by janhavikale06** [Lakhankumawat/LearnCPP#1120]
### Description

Insertion operation of linked list adds an item to the linked list. We know that whenever a data item is added to the linked list, we need to change the next pointers of the previous and next nodes of the new item that we have inserted.
In Linked list , we can add a new node -
1. At the beginning
2. At the end
3. At the middle.

Deleting a node from a linked list also involves various positions from where the node can be deleted. After deletion, we need to adjust the next pointer and the other pointers in the linked list appropriately so as to keep the linked list intact.
We can remove a node -
1. from beginning
2. from end 
3. from a particular location.

### Domain

Data Structure

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by harshit078** [comment]
Hi Janhavi, I can solve this issue easily. Could you assign this to me?

**Comment by NamanKothari5** [comment]
Please assign this to me!
