### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by lagwalsahil21821** [Lakhankumawat/LearnCPP#113]
### Description

Given n sorted numbers(duplicates) and you have to implement binary search algo and gave output as the number is present or not? 
If present then at what index? And if that element has duplicates then print that index at which it has first occurred.

like we have 7 elements
**Input:** 
2 4 4 4 7 7 9
binary Search for : 4
**Output:**
4 is present at index 1

@Lakhankumawat Please consider the issue and assign it to me. Thank you.
I'm a **GSSoC 2022** participant.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Poojaamangal** [comment]
please have look at this @n4i9kita

**Comment by n4i9kita** [comment]
@lagwalsahil21821 go forth with the second part, i.e. find the index of first and the last occurrence of an element in a sorted array. 

Make two separate functions : (1) 1st occurrence, (2) 2nd occurrence.

As an extension... you can write a third function to print the count of an element in a sorted array.

Take the input array and the element to be searched from the user.

**Comment by n4i9kita** [comment]
@lagwalsahil21821, update the title, too.

**Comment by Lakhankumawat** [comment]
Please also mention in which directory of project will your algorithm or problem-statement will go .

**Comment by Lakhankumawat** [comment]
Depending on your response will decide to accept your issue or not .

**Comment by lagwalsahil21821** [comment]
> @lagwalsahil21821 go forth with the second part, i.e. find the index of first and the last occurrence of an element in a sorted array.
> 
> Make two separate functions : (1) 1st occurrence, (2) 2nd occurrence.
> 
> As an extension... you can write a third function to print the count of an element in a sorted array.
> 
> Take the input array and the element to be searched from the user.

ok. I'll do it

**Comment by Sakshi-209** [comment]
hey!
please assigned me this issue under gssoc'22
thanks
sakshi
