### ISSUE TITLE
Adding Digits Problem

### ISSUE THREAD

**Issue by Kranthi-Guribilli** [Lakhankumawat/LearnCPP#114]
### Description

Two inputs are given: a and b. However, the number 'a' is too short. So we should repeat the operation of lengthening the number 'a' n times.

One operation of lengthening a number means adding exactly one digit to the number (in the decimal notation) to the right provided that the resulting number is divisible by the number b. If it is impossible to obtain the number which is divisible by b, then the lengthening operation cannot be performed.

The task is to print the number we can get after applying the lengthening operation to the number 'a' n times if possible else print -1.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

Please assign this to me!
I'm a GSSOC'22 contributor.

**Comment by Poojaamangal** [comment]
please have look at this @iamgunjan

**Comment by Kranthi-Guribilli** [comment]
@miraj0507 please assign this issue to me.
