### ISSUE TITLE
Add some Questions in linked list

### ISSUE THREAD

**Issue by 89-manshi** [Lakhankumawat/LearnCPP#1148]
### Description

I want to add some standard questions of linkedlist like check weather loop present in linked list or not , concatenate 2 linked list and many more
kindly assign this to me under gssoc 22 . It 'll help  the learners .

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by sonalee21** [comment]
Hello,
I would like to work on this issue, please assign it to me.
