### ISSUE TITLE
Adding subsequence with K sum problem 

### ISSUE THREAD

**Issue by LakshayN** [Lakhankumawat/LearnCPP#115]
### Description

Given a vector and a number K, the task is to find all the subsequences of the vector whose sum of elements is K.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by LakshayN** [comment]
@Lakhankumawat I got a mail that says "Greetings: All jobs have failed" after I raised this issue. What does that mean ?

**Comment by miraj0507** [comment]
Make sure you give the O(n) solution as well, or else I need to drop down the level from level2 to level1

**Comment by LakshayN** [comment]
Hi @Lakhankumawat please merge the PR corresponding to this issue. It's been so long
