### ISSUE TITLE
0-1 Knapsack

### ISSUE THREAD

**Issue by shivam-s16** [Lakhankumawat/LearnCPP#116]
### Description

I wish to implement other knapsack like integer and 0-1 . @Lakhankumawat and want to work  on it as GSSoC'22  participant .

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Poojaamangal** [comment]
pleae have a look at this @miraj0507

**Comment by miraj0507** [comment]
@shivam-s16 Kindly update the title as 0-1 knapsack.

**Comment by shivam-s16** [comment]
@miraj0507 updated the title thanks for suggesting
