### ISSUE TITLE
Checking if Password contains part of Username of not

### ISSUE THREAD

**Issue by rtp77** [Lakhankumawat/LearnCPP#117]
### Description

Description

To create a simple search upon input of Username and Password, to check if password contains bits of username or not, in order to determine the strength of the password for such cases.

In addition, will include the description of the code and time complexity.

I would love to work on this as part of GSSoC 22

### Domain

Other

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Poojaamangal** [comment]
please have look at this  @miraj0507

**Comment by miraj0507** [comment]
I am sorry for now we are not accepting Problem Statements, kindly go through other folders and create a best fit algorithm, We soon gonna conduct a meeting where everything is going to be clear.
