### ISSUE TITLE
Printing Subsequences whose sum is equal to n

### ISSUE THREAD

**Issue by stutimohta20** [Lakhankumawat/LearnCPP#1171]
### Description

Printing subsequences from an array whose elements combine to give a sum equal to n(given value)  using recursion

### Domain

Data Structure

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by stutimohta20** [comment]
Please Assign this issue to me

**Comment by stutimohta20** [comment]
@Lakhankumawat please assign this to me

**Comment by AaliyahBeg** [comment]
I would love to contribute, @Lakhankumawat please assign this issue. Thanks!
