### ISSUE TITLE
Implement intersection of 2 arrays

### ISSUE THREAD

**Issue by 89-manshi** [Lakhankumawat/LearnCPP#1181]
### Description

I want to implement intersection of 2 arrays. 
pls assign this to me under gssoc'22.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by sonalee21** [comment]
Hello!
I would like to work on this, please assign it to me under GSSoC 22.
