### ISSUE TITLE
Vertical traversal of a tree

### ISSUE THREAD

**Issue by eswarbhageerath** [Lakhankumawat/LearnCPP#1192]
### Description

I want to add a code which prints the vertices of a tree in vertical order

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by deepan773399** [comment]
I want to work on this issue . Please assign it to me .

**Comment by eswarbhageerath** [comment]
@Mrjoy832 @Lakhankumawat Why aren't you replying to this?

**Comment by Mrjoy832** [comment]
> @Mrjoy832 @Lakhankumawat Why aren't you replying to this?

What's Your question??????
