### ISSUE TITLE
array intersection

### ISSUE THREAD

**Issue by deekshhaa** [Lakhankumawat/LearnCPP#1201]
### Description

You have been given two integer arrays/list(ARR1 and ARR2) of size N and M, respectively. You need to print their intersection; An intersection for this problem can be defined when both the arrays/lists contain a particular value or to put it in other words, when there is a common value that exists in both the arrays/lists.

INPUT
2 3 4 5 6
2 4 9

OUTPUT
2 4

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by SonakshiGoyal** [comment]
I can work on it. Please assign it to me.

**Comment by Rishita489** [comment]
hey I am a GSSOC'22 contributor . Can you please assign this issue to me .
