### ISSUE TITLE
Check palindrome using recursion

### ISSUE THREAD

**Issue by deekshhaa** [Lakhankumawat/LearnCPP#1204]
### Description

**CHECK PALINDROME**

You are given a string s, check whether the string is palindrome or not through recursion. Write a function and return true if yes and false if no. 

Palindrome: A palindrome is a word, number, phrase, or other sequence of characters which reads the same backward as forward, such as madam or racecar.  

INPUT:
learncpp

OUTPUT:
false

INPUT:
learncppcnrael

OUTPUT:
true

INPUT
rotator

OUTPUT:
true

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by SonakshiGoyal** [comment]
I can work on it. Please assign it to me.
