### ISSUE TITLE
STL

### ISSUE THREAD

**Issue by deekshhaa** [Lakhankumawat/LearnCPP#1205]
### Description

STANDARD TEMPLATE LIBRARY(STL)

Add Keywords that are helpful in competitive programming. 

### Domain

Standard Template Library

### Type of Contribution

Addition, Enhancement, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by deepan773399** [comment]
I can work on this issue . Please assign it to me.
