### ISSUE TITLE
Iterative merge sort algorithm

### ISSUE THREAD

**Issue by Rahul2570089** [Lakhankumawat/LearnCPP#121]
I would like to add Iterative version of merge sort algorithm (which was missing in "S-SortingAlgorithm" folder) with all the necessary description like time and space complexity or any comments for more clarity.
Hope you will assign this task to me.

**Comment by Poojaamangal** [comment]
please have look at this @miraj0507

**Comment by i-am-aisha** [comment]
Greetings sir!
I hold a strong grip on DSA specially on sorting algorithms  and I think I can provide optimal solution of iterative merge sort algorithm with proper comments with mentioning time complexity of every step .I am a GSSOC'22 contributor and I want to contribute in your project so please assign me this issue.
Thankyou!

**Comment by miraj0507** [comment]
> Greetings sir!
> 
> I hold a strong grip on DSA specially on sorting algorithms  and I think I can provide optimal solution of iterative merge sort algorithm with proper comments with mentioning time complexity of every step .I am a GSSOC'22 contributor and I want to contribute in your project so please assign me this issue.
> 
> Thankyou!

Hey,kindly create a new issue and give the best shot algorithm that you can get you an approval, according to the GSSoc guidelines we can only give it to the FIRST COME FIRST SERVE, kindly create your own issue. we are more than happy to review
