### ISSUE TITLE
Sort an array of 0s, 1s and 2s

### ISSUE THREAD

**Issue by PriyanshuSaxena2612** [Lakhankumawat/LearnCPP#124]
### Description
I will be writing **2 methods** for the above problem statement, continued **with time and space complexity**, first one is the basic with counting all the 0, 1 and 2 while the other method is to swap the arrays' elements in place in a single traversal.

### Domain
Array Data Structure

### Type of Contribution
Addition

### Code of Conduct
 I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by PriyanshuSaxena2612** [comment]
I am a GSSOC contributor, please assign me this issue.

**Comment by Nanzzie** [comment]
I am a GSSOC'22 contributor, and I would like to add the code for the above problem statement. Please allow me to work on this issue.

Domain: Array Data Structure

Type of Contribution: Addition

Code of Conduct
I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

Domain
Data Structure

Type of Contribution
Addition

Code of Conduct
 I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by PriyanshuSaxena2612** [comment]
@Lakhankumawat, please assign me this issue to work on!

**Comment by miraj0507** [comment]
Hello, kindly update the title , Dutch National Flag Algorithm o(N) is only going to be accepted.

**Comment by miraj0507** [comment]
No you can continue with both.
