### ISSUE TITLE
Find All Duplicates in An array

### ISSUE THREAD

**Issue by nouraan-ahmed** [Lakhankumawat/LearnCPP#1240]
### Description

Given an integer array nums of length n where all the integers of nums are in the range [1, n] and each integer appears once or twice, return an array of all the integers that appears twice.

You must write an algorithm that runs in O(n) time and uses only constant extra space.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Anjali-Chaudhary3** [comment]
@Lakhankumawat i am not able to fork the repo ............it is showing No more forks can be created. [View existing forks.]
