### ISSUE TITLE
Add Simple, Circular, Reverse and Merge2Sorted Linked List Programs

### ISSUE THREAD

**Issue by Susmita-Dey** [Lakhankumawat/LearnCPP#126]
### Description

I want add the above mentioned 4 programs to the Linked List folder of this repo.
**I am contributor at GSSoC'22. Please assign this issue to me.**

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Poojaamangal** [comment]
please have look at this @n4i9kita

**Comment by i-am-aisha** [comment]
Greetings sir!
I solved a lot of questions on data structures and algorithms ,I can provide one of the best solution of this issue  and want to contribute these four programs  with proper comments with mentioning time complexity of every step .I am a GSSOC'22 contributor and I want to contribute in your project so please assign me this issue.
Thankyou!

**Comment by miraj0507** [comment]
Hello, kindly select one single problem statement per issue.

**Comment by Susmita-Dey** [comment]
> Hello, kindly select one single problem statement per issue.

Okay, I would like add the Circular Linked list first. I'm a GSSoC'22 contributor. Kindly assign it to me.
