### ISSUE TITLE
Delete duplicate nodes from unsorted linked list 

### ISSUE THREAD

**Issue by Gyani1610** [Lakhankumawat/LearnCPP#1262]
### Description

The problem is to take a list and delete any duplicate nodes from the list. The list is unsorted. For example if the linked list is 12->11->12->21->41->43->21 then removeDuplicates() should convert the list to 12->11->21->41->43. 

I will be explaining and writing the code to delete duplicate nodes from unsorted linked list with a time complexity of O(n) and a space complexity of O(n). The method I will be using is Hashing. We traverse the link list from head to end. For every newly encountered element, we check whether it is in the hash table: if yes, we remove it; otherwise we put it in the hash table.

I am a participant at GSSoC'22.

@Lakhankumawat I want to work on this issue, can you please assign this to me?

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by durgesh-4526** [comment]
I have solved this issue kindly check It and merge it @Lakhankumawat

**Comment by Gyani1610** [comment]
I have created this issue. So please assign it to me.
