### ISSUE TITLE
Height of a binary search tree

### ISSUE THREAD

**Issue by SupriyaGembali** [Lakhankumawat/LearnCPP#1281]
### Description

When a binary search tree is given as input, We can find its height by the following process.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by navyasharma0203** [comment]
Can I work on this??
