### ISSUE TITLE
Multithreaded merge sort

### ISSUE THREAD

**Issue by adham-nasr** [Lakhankumawat/LearnCPP#132]
**Description**

I suggest an Algorithm to merge sort an array with multiple threads
Time complexity - O(nlog(n)).

**Domain**
Algorithm

**Type of Contribution**
Addition

**Code of Conduct**
 I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Please mention the directory in which you'll be adding this algorithm or problem statement .
Your idea seems good but please describe it and i'll be glad to accept it .

**Comment by adham-nasr** [comment]
algorithm should be added to the S-SortingAlgorithms  directory

**Comment by adham-nasr** [comment]
**Additional problem description:** 

![Capturesend](https://user-images.githubusercontent.com/60667591/156886127-8ac4b070-8f2c-44b6-8255-ce79d5b3d75a.PNG)
