### ISSUE TITLE
Merge Point of Two Linked Lists

### ISSUE THREAD

**Issue by akanksha0209** [Lakhankumawat/LearnCPP#1338]
### Description

Given pointers to the head nodes of linked lists that merge together at some point, we will find the node where the two lists merge. The merge point is where both lists point to the same node, i.e. they reference the same memory location. It is guaranteed that the two head nodes will be different, and neither will be NULL. If the lists share a common node, we will return that node's data value. 

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Diishasing** [comment]
hi @Lakhankumawat please assign it to me
