### ISSUE TITLE
Binary Tree Right Side View

### ISSUE THREAD

**Issue by R-Ayush777** [Lakhankumawat/LearnCPP#1342]
### Description

I wanted to add new algorithm **Binary Tree Right Side View**.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Diishasing** [comment]
hi @R-Ayush777  @Lakhankumawat please assign it to me
