### ISSUE TITLE
Improve the Footer -(UI/UX)

### ISSUE THREAD

**Issue by Kunal0220** [Lakhankumawat/LearnCPP#1356]
### Description

The footer of the website doesn't go with the content of the webpage . I would like to make it properly placed and add some more options like [Link to GitHub repository] , [©] and [how to contribute in the community] to it .

This enhancement will not affect any of the existing content of the footer , In turn it will have some more css .

If the changes I have proposed need some alteration or any kind of deviation from the option , I will make the necessary changes.

Existing Footer:
<img width="1428" alt="Screenshot 2022-05-06 at 11 49 53 PM" src="https://user-images.githubusercontent.com/71934168/167195844-216be4e8-0653-4b89-a303-02a5dd9f1f78.png">

### Domain

UI/UX

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by tasneemahmed123** [comment]
can you assign me this issue?

**Comment by Kunal0220** [comment]
@tasneemahmed123 , actually I too am not being able to get the files where we can apply the changes , I am waiting for the maintainer to respond .
