### ISSUE TITLE
Cycle Sort

### ISSUE THREAD

**Issue by SupriyaKumari08** [Lakhankumawat/LearnCPP#1359]
### Description

Algorithm and code for cycle sort under Sorting Algorithms along with proper explanation and some practise problems.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Diishasing** [comment]
hi please assign it to me
