### ISSUE TITLE
merge two sorted array without using extra space ( Gap Method )

### ISSUE THREAD

**Issue by Yash-Parsana** [Lakhankumawat/LearnCPP#136]
### Description

merge two sorted array without using extra space

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Yash-Parsana** [comment]
i would like to work on it under Gssoc22

**Comment by Lakhankumawat** [comment]
Only one issue at a time by one contributor sorry
