### ISSUE TITLE
Power of A number using recursion

### ISSUE THREAD

**Issue by SanyaGera** [Lakhankumawat/LearnCPP#1371]
### Description

To calculate power of a number using recursion using two approaches.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by tasneemahmed123** [comment]
hi , can you assign me this issue?
