### ISSUE TITLE
Rotate Image

### ISSUE THREAD

**Issue by shr-code** [Lakhankumawat/LearnCPP#1380]
### Description

You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image [in-place](https://en.wikipedia.org/wiki/In-place_algorithm), which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.
![image](https://user-images.githubusercontent.com/84399701/167284154-4ce78f6a-f5b4-4dfa-b78b-d964cd0e670c.png)

This question is from leetcode with a difficulty level of medium.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by shr-code** [comment]
@aditi944 please assign this issue to me. I have created a pr for the earlier issue. But it is yet to be reviewed

**Comment by aditi944** [comment]
It is already assigned to you

**Comment by shr-code** [comment]
the bot has unassigned me

**Comment by aditi944** [comment]
ok,let me see
