### ISSUE TITLE
Remove Nth Node From End of List

### ISSUE THREAD

**Issue by ayushi1210** [Lakhankumawat/LearnCPP#1393]
### Description

Given the head of a linked list, remove the nth node from the end of the list and return its head.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by tasneemahmed123** [comment]
hi, can you assign me this issue?

**Comment by ayushi1210** [comment]
Please assign this issue to me.
