### ISSUE TITLE
Preorder Traversal Of a Tree

### ISSUE THREAD

**Issue by Anuragkr07** [Lakhankumawat/LearnCPP#1394]
### Description
I want to add the iterative version of the preorder traversal of a Binary Tree in the Binary Tree folder which is a sub folder of Trees.

Problem Description:
In preorder traversal, first, the root node is visited, then the left sub-tree, and after that right sub-tree is visited. The process of preorder traversal can be represented as -
Root -> Left -> Right
So if the tree is:
```
          1
         /  \
       2     3
     /   \
   4      5
```

the preorder traversal of this tree will be :
1 -> 2 -> 4 -> 5 -> 3

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by navyasharma0203** [comment]
Can I work on this issue??
