### ISSUE TITLE
Sorting array using Quicksort

### ISSUE THREAD

**Issue by neeluyadav999** [Lakhankumawat/LearnCPP#1415]
### Description

It is based on  divide and conquer algorithm.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by navyasharma0203** [comment]
Can I work on this??
