### ISSUE TITLE
Matrix Chain Multiplication 

### ISSUE THREAD

**Issue by Khushi-Mattu** [Lakhankumawat/LearnCPP#1428]
### Description

Matrix Chain Multiplication under dynamic programming

### Domain

Algorithm

### Type of Contribution

Addition, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by durgesh-4526** [comment]
Kindly check my PR #1465

**Comment by Khushi-Mattu** [comment]
i made the issue so shouldnt it have been assigned to me?
