### ISSUE TITLE
Strassen's matrix multiplication

### ISSUE THREAD

**Issue by 22chiragmodh** [Lakhankumawat/LearnCPP#143]
### Description

Strassen's matrix multiplication Time complexity : O(n^log7)
Naïve matrix multiplication Time Complexity: O(N^3)

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by 22chiragmodh** [comment]
Strassen's matrix multiplication time complexity < Naïve matrix multiplication .
Strassen's matrix multiplication is uses divide and conquer method which is a recursive algorithm.

**Comment by Lakhankumawat** [comment]
Please find the directory in which your problem statement will go and mention it here .

**Comment by Lakhankumawat** [comment]
Also make a clear and concise Desc. of your Problem then short-desc label will be removed and you'll be assigned this issue .

**Comment by 22chiragmodh** [comment]
**Problem**

Divide and conquer method main component for high time complexity is 8 recursive calls but Strassen algorithm is use to reduce the number of recursive call to 7 and also Divide and conquer matrix multiplication Time complexity is greater than Strassen matrix multiplication.

**Description**

Strassen's matrix multiplication is uses divide and conquer method which is a recursive algorithm.
In Strassen matrix Multiplication method we have also divide matrices to sub-matrices of size N/2 x N/2.

The four sub-matrices of result are like below:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/91516739/156193380-73a436a5-898c-45c0-a2a7-22dd4e9e0317.png">

Time complexity of Divide and Conquer method is O(N^3) because we do 8 multiplications for matrices of size N/2 x N/2 and 4 additions. 
T(N) = 8T(N/2) + O(N^2) .

Time Complexity of Strassen Method is O(N^log7) because we do we do 7 multiplications for matrices of size N/2 x N/2 and additions & Subtraction. 
T(N) = 7T(N/2) + O(N^2) .

**Directory**

D-DivideAndConquerAlgorithms

I'm Modh Chirag contributor of GSSOC'22. Please assign me this issue.
