### ISSUE TITLE
Word Search

### ISSUE THREAD

**Issue by Rishabh-Gaud** [Lakhankumawat/LearnCPP#1431]
### Description
This is one of the base-building questions for backtracking and recursion.
Description

Given an m x n grid of characters board and a string word, return true if word exists in the grid.

The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.

 
![image](https://user-images.githubusercontent.com/65586827/168332340-9b251094-c276-4f0a-b723-9e262907b409.png)

**Input**: board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCCED"
**Output**: true

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by navyasharma0203** [comment]
@Rishabh-Gaud Can I work on this??
