### ISSUE TITLE
Rotate a matrix by 90 degree in clockwise direction without using any extra space

### ISSUE THREAD

**Issue by Yash-Parsana** [Lakhankumawat/LearnCPP#144]
### Description

matrix rotation

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Yash-Parsana** [comment]
i would like to work on it under Gssoc22

**Comment by Lakhankumawat** [comment]
Issue Spamming .
