### ISSUE TITLE
Longest Palindrome in a String

### ISSUE THREAD

**Issue by Yash-Parsana** [Lakhankumawat/LearnCPP#145]
### Description

program to find longest palindromic substring in a string

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Please make a clear and concise description of your issue .

**Comment by Yash-Parsana** [comment]
program to find longest palindromic substring in a string

**Comment by Lakhankumawat** [comment]
Yaa but edit the description above not in comments bro.

**Comment by Lakhankumawat** [comment]
This issue will be commited in S-Strings

**Comment by Lakhankumawat** [comment]
And do not spam multiple issues.

**Comment by Yash-Parsana** [comment]
what the status ?
