### ISSUE TITLE
Next Permutation

### ISSUE THREAD

**Issue by Yash-Parsana** [Lakhankumawat/LearnCPP#146]
### Description

Algorithm to generate Next Permutation of a number

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Yash-Parsana** [comment]
@Lakhankumawat 
i would like to work on it under Gssoc22

**Comment by Lakhankumawat** [comment]
Only one issue can be assigned to one contributor at a time you have made two issues .

**Comment by Lakhankumawat** [comment]
either close this one or existing one

**Comment by Yash-Parsana** [comment]
> Only one issue can be assigned to one contributor at a time you have made two issues .
@Lakhankumawat 
i didn't know that so created many issue. now what to do ?

**Comment by Lakhankumawat** [comment]
I'll help you close them .
