### ISSUE TITLE
Sort a Stack

### ISSUE THREAD

**Issue by nishkarsh800** [Lakhankumawat/LearnCPP#1461]
### Description

This is a basic problem in Stack data structures.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by navyasharma0203** [comment]
Can I work on this??
