### ISSUE TITLE
Implementation of Queue using Stack

### ISSUE THREAD

**Issue by rravi1401** [Lakhankumawat/LearnCPP#147]
### Description

I'll write and explain code regarding this data structure .
In this we will learn how to implement Queue data structure through the help of Stack.
Queue is a data structure which works on FIFO pattern but we will implement it with through Stack which works on LIFO princile.
I'll really like to contribute on this issue by writing code of all function (insertion, deletion) all and also add comments to explain this.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rravi1401** [comment]
I'm a contributor under gssoc 22 . And I would like to work on this issue

**Comment by rravi1401** [comment]
@Lakhankumawat will you please assign this issue to me , I'm gssoc22 participant.

**Comment by Lakhankumawat** [comment]
ok @rravi1401  you are assigned to this issue make sure you follow contribution guidelines and commit your problem statement in proper folder i.e. S-Stacks  and do not create multiple issues at the same time . You can only work on one issue at a time .
