### ISSUE TITLE
Two Sum Leetcode

### ISSUE THREAD

**Issue by aditya-gaikwad** [Lakhankumawat/LearnCPP#15]
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Output: Because nums[0] + nums[1] == 9, we return [0, 1].

Solution:

class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        vector<int> v, ans;
        int l = 0, r = nums.size() - 1, n1, n2;
        v = nums;
        sort(nums.begin(), nums.end());
        while(l < r)
        {
            if(nums[l] + nums[r] > target) r--;
			else if(nums[l] + nums[r] < target) l++;
			else{
				n1 = nums[l], n2 = nums[r];
				break;
			}
        }
        for(int i = 0; i < v.size(); i++)
        {
            if(v[i] == n1 || v[i] == n2)
            {
                ans.push_back(i);
            }
            if(ans.size() == 2)
                break;
        }
        return ans;
    }
};

**Comment by aditya-gaikwad** [comment]
.

**Comment by Lakhankumawat** [comment]
No not like this , in level 1 in cpp file itself you can include the details for the problem statement along with the link

**Comment by aditya-gaikwad** [comment]
Sorry, but I am not able to get the location of the folder you are talking about

**Comment by aditya-gaikwad** [comment]
Got it. Thanks!
