### ISSUE TITLE
Jump Search

### ISSUE THREAD

**Issue by VaibhavMogha** [Lakhankumawat/LearnCPP#150]
### Description

Hi
I am a contributor at GSSOC'22, and I would like to contribute and add Jump Search, A searching algorithm. I will even add explanations and details like time/space complexity etc.
Can you please assign this issue to me?
Thank you!

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by VaibhavMogha** [comment]
@Lakhankumawat Please assign this to me.
Thank you!

**Comment by Lakhankumawat** [comment]
Please mention the directory in which you'll be adding this algorithm or problem statement .
Your idea seems good but please describe it and i'll be glad to accept it .

**Comment by VaibhavMogha** [comment]
Hey, @Lakhankumawat @miraj0507 Should I start working on it?
Thank you!

**Comment by VaibhavMogha** [comment]
Hey, @miraj0507 @iamgunjan @Lakhankumawat Please assign this issue to me.
Thank you!

**Comment by VaibhavMogha** [comment]
Hey, @miraj0507 @iamgunjan @Lakhankumawat Please assign this issue to me.
Thank you!

**Comment by Hend123** [comment]
\assign
