### ISSUE TITLE
nth Fibonacci Number using Matrix

### ISSUE THREAD

**Issue by IKRA786** [Lakhankumawat/LearnCPP#151]
### Description

As a GSSOC'22 contributor, I would like to add clean code for finding nth Fibonacci number using Matrix which is the most optimized approach when input is something like   1<=N<=10^9 as we can't use O(N) approach. Here comes the role of the matrix method that optimizes T.C to O(LogN)
Please assign this to me.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Please stop spamming issues you've been already assigned an issue #122
