### ISSUE TITLE
Implementing Queue using Linked List

### ISSUE THREAD

**Issue by rtp77** [Lakhankumawat/LearnCPP#153]
### Description

Description

I would like to create a queue using a linked list where data is allocated dynamically
The process starts with creating a new node and if the queue is empty and the next node added to the front and the next pointer of next towards null, if it contains an element then it will not be null so the next pointer points to new node pointer and that towards the new node pointer, by doing this we add the element to the queue.
I will give proper documentation and time complexity;
I would like to work on this for GSSoC 22.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by kalash2205** [comment]
hi @Lakhankumawat please assign me to this issue
