### ISSUE TITLE
Add Data Structures and Algorithms in A- Arrays file.

### ISSUE THREAD

**Issue by nikhil25803** [Lakhankumawat/LearnCPP#154]
### Description

Hi, I am Nikhil Raj. I'm a GSSoC participant.
I want to add all the Data Structures and Algorithms related to Arrays in A-Arrays file with proper documentation as the file is empty. I'm really want to contribute in this
Can you please assign it to me?

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by nikhil25803** [comment]
Hey @Lakhankumawat . Please assign it to me

**Comment by iamgunjan** [comment]
@Lakhankumawat kindly have a look

**Comment by nikhil25803** [comment]
> @Lakhankumawat kindly have a look

Yes, I checked. The A-Array folder is empty. There is no Kadane's Algorithm or Dutch National Flag Algorithm in that folder. Even the readme file is empty. I would like to add all those in a structured manner. So can you please assign it to me?

**Comment by n4i9kita** [comment]
@nikhil25803, pick one algorithm that you wish to implement, and no else has raised an issue and assigned the same. 

You can work on one algorithm at a time, so just one issue at a time. 
Either mention the algorithm that you will be working on here, or create a new issue with proper description of the algorithm that you wish to implement, along with time complexity and other details.

**Comment by nikhil25803** [comment]
I want to add Kadane's Algorithm which is used to find the maximum possible sum of a contiguous sub-array. It will be of time complexity O(N), where N is the number of elements in the array.

**Comment by miraj0507** [comment]
@nikhil25803 kandes have already been taken up by someone earlier , you need to go with something else
