### ISSUE TITLE
Inserting a node in doubly linked list

### ISSUE THREAD

**Issue by mjaya25** [Lakhankumawat/LearnCPP#161]
### Description

Insert the node at nth position in the doubly linked list and display the linked list. 

I will provide  the code with time and space complexity 
please assign this to me. I am participating in gssoc'22.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by kalash2205** [comment]
@Lakhankumawat please assign me to this issue

**Comment by Bhavneet345** [comment]
Please, assign me this issue I can provide a solution to this problem by solving it with an Object-Oriented Programming approach.

**Comment by KhushiRana2003** [comment]
PLease assign this to me .. I  will work on this through a good approach. i am also gssoc 2022 participant..

**Comment by Princeton21** [comment]
!assign
