### ISSUE TITLE
Creating and Displaying a Linked List

### ISSUE THREAD

**Issue by shivanithorve01** [Lakhankumawat/LearnCPP#162]
### Description

I am GSSoC Contributor. There is no code for creating and displaying a Linked List in L-Linked List folder. So I want to add it. 
@Lakhankumawat Please assign this issue to me.
Additionals -
Should I add some more functions such as  :
1. Insert a node at first index and at a particular index
2. Delete a node 

### Domain

Data Structure

### Type of Contribution

Addition, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Aneesh-07** [comment]
I would like to work on this issue under GSSoC 2022

**Comment by chandan9369** [comment]
@iamgunjan  I want to work on this issue as a GSSOC 22 contributor please assign me.

**Comment by rutika1823** [comment]
I would like to work on 2nd issue under GSSoC 2022 Can you please assign this to me

**Comment by n4i9kita** [comment]
@shivanithorve01, one issue at a time. You cannot create another issue until an issue has, been resolved, closed or merged. Please choose one of your issues, and we  will close the other issues. 
Make sure to keep this in mind in the future.

**Comment by shivanithorve01** [comment]
@n4i9kita Sorry for the inconvenience caused. It won't happen later. My PR is approved for previous issue and I have closed my other issue as well. So kindly assign this issue to me.

**Comment by Sakshi-209** [comment]
hey!
please assigned me this issue under gssoc'22
thanks
sakshi

**Comment by shivanithorve01** [comment]
Please assign this issue to me @iamgunjan @n4i9kita @miraj0507 . I am done with my previous PR.
