### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by ritikaaaa177** [Lakhankumawat/LearnCPP#167]
### Description

You are given a sorted array "arr" of n elements. Given a number d, you have to find it's first  occurrence in the array as well as its last occurrence. The array may contain duplicates.

Example

Find first & last occurrence of 33 in the given array:

Array arr = {1, 2, 9, 15, 22, 33, 33, 33, 33, 33, 39, 40, 55, 66, 77}.

Hence, the answer will be 5 and 9 respectively (0-based indexing).

### Domain

Algorithm

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rahulXbarnwal** [comment]
@Lakhankumawat Will you please Assign this issue to me. I am GSSOC'22 participant.

**Comment by kalash2205** [comment]
please assign me to this issue

**Comment by Anand-Anurag** [comment]
I can solve this issue in O(log(n)) time and O(1) space, Please assign thos issue to me @Lakhankumawat @iamgunjan

**Comment by miraj0507** [comment]
Binary search has already been assigned to someone earlier, can you modify your problem with binary search? There is so much one can do with binary search??

**Comment by ritikaaaa177** [comment]
Hello @miraj0507 now please assign this to me I have made required changes.
