### ISSUE TITLE
Palindrome Check using recursion

### ISSUE THREAD

**Issue by mehakk-Bhatia** [Lakhankumawat/LearnCPP#170]
### Description

In this problem , we are given a string and our task is to check whether the string is palindrome or not recursively.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by KhushiRana2003** [comment]
Please assign this to me I am gssoc participant and want to work on this issue.. As I have already solved this problem

**Comment by AsmaaHeikal** [comment]
please assign this to me . l want to work on it.
