### ISSUE TITLE
calculating x^n in O(log(n)) 

### ISSUE THREAD

**Issue by adham-nasr** [Lakhankumawat/LearnCPP#171]
### Description

**Description**
calculating power(x,n) using divide and conquer 

Time complexity : O(log(n))
Space Complexity: O(1) 
### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by adham-nasr** [comment]
directory : D-DivideAndConquerAlgorithms

**Comment by kalash2205** [comment]
please assign me this issue @Lakhankumawat

**Comment by Anand-Anurag** [comment]
I'll use Binary Exponentiation and Dynamic Programming to solve this in O(log(n) time and O(1) Space, Please assign this issue to me @Lakhankumawat , I'm a contributor

**Comment by adham-nasr** [comment]
Pull request sent
