### ISSUE TITLE
Largest Rectangular Area in a Histogram using stacks

### ISSUE THREAD

**Issue by LakshayN** [Lakhankumawat/LearnCPP#173]
### Description

Find the largest rectangular area possible in a given histogram where the largest rectangle can be made of a number of contiguous bars.
For example, consider the following histogram with 7 bars of heights {6, 2, 5, 4, 5, 1, 6}. The largest possible rectangle possible is 12

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by chandan9369** [comment]
Hey @iamgunjan i want to solve this issue please assign me this issue so that i start working on this issue.

**Comment by LakshayN** [comment]
@iamgunjan @chandan9369  this issue was raised by me so that its assigned to me

**Comment by chandan9369** [comment]
@LakshayN till now this issue is not assigned to anyone that is why i asked for.

**Comment by LakshayN** [comment]
hi, please merge this pr, its been so long
