### ISSUE TITLE
 Detect a cycle in an undirected graph 

### ISSUE THREAD

**Issue by emzm17** [Lakhankumawat/LearnCPP#177]
### Description

Using Disjoint Set

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by chandan9369** [comment]
@emzm17  i want to work on this issue under GSSOC 22 so please assign me so that i start working on this issue

**Comment by AshmitKesarwani** [comment]
@emzm17 Sir I would like to take this , Can you Please assign me ?
I have understood the problem and can Implement it in O(V+E) time using a optimal DFS approach .

I am also a participant of GSSoC'22.
