### ISSUE TITLE
Addition of all D-Division and Conquer Algorithm techniques

### ISSUE THREAD

**Issue by kusumita29** [Lakhankumawat/LearnCPP#178]
### Description

Since Divide and Conquer algorithm is very useful for searching and sorting huge sets of data, I would like to add the files and code for this algorithm with proper explanation and the time complexity for each method.

I would like to contribute to it under GSSOC'22. 

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by n4i9kita** [comment]
@kusumita29, be more specific. Nothing like "all" the algorithms. Pick one and mention it here, or we would close this issue, and you can create a new one for the same.

**Comment by kusumita29** [comment]
@n4i9kita I would like to contribute on Quick Sort algorithm under DAC technique.

**Comment by AshmitKesarwani** [comment]
@n4i9kita  Ma'am I would like to take this , Can you Please assign me ?
I have understood the problem and can contribute on Binary Search Algorithm i.e. under DC .

I am also a participant of GSSoC'22.
