### ISSUE TITLE
Add Queue, Priority Queue and Stacks in STL

### ISSUE THREAD

**Issue by nikhil25803** [Lakhankumawat/LearnCPP#182]
### Description

I want to add Queue, Priority Queue, Deque, and Stack in the STL folder as a contribution under GSSoC 2022.
Please assign it to me

### Domain

Standard Template Library

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Poojaamangal** [comment]
Hey @nikhil25803  , make your issue a descriptive one so it is easy for us.

**Comment by nikhil25803** [comment]
Queue, Priority Queue, Deque, and Stack are the container adaptors that help to implement sequential containers in a different manner. Where Stack (a LIFO data structure) and Queue(a FILO data structure). I found these files missing in the Containers section of the STL folder in this repository. I want to add  their programs with all methods mentioned like push(), pop(), top(), size(), etc. So please assign it to me so that I can start working on this.

**Comment by nikhil25803** [comment]
Thank You. On it!

**Comment by nikhil25803** [comment]
Hey @miraj0507 can I connect with you on LinkedIn so that I can ask something if needed and can keep you updated with my work?
