### ISSUE TITLE
Rabin-Karp Algorithm for Pattern Searching

### ISSUE THREAD

**Issue by Yash-Parsana** [Lakhankumawat/LearnCPP#183]
### Description

Rabin karp algorithm is pattern searching algorithm like kmp algorithm 
Rabin Karp algorithm matches the hash value of the pattern with the hash value of current substring of text, and if the hash values match then only it starts matching individual characters.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Yash-Parsana** [comment]
i would like to work on it under Gssoc22

**Comment by AshmitKesarwani** [comment]
@miraj0507 Sir I would like to take this , Can you Please assign me ?
I have understood the problem and can contribute towards this.

I am also a participant of GSSoC'22.

**Comment by Yash-Parsana** [comment]
i would like to work on it under Gssoc22
