### ISSUE TITLE
Readme file for STL

### ISSUE THREAD

**Issue by nikhil25803** [Lakhankumawat/LearnCPP#184]
### Description

I want to add a readme file for STL with proper documentation and resources.
Please assign it to me.

### Domain

Standard Template Library

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by n4i9kita** [comment]
@nikhil25803 please be more descriptive about what you plan to add in the documentation section for STL

**Comment by n4i9kita** [comment]
@nikhil25803, one issue at a time. Pick the one that you wish to work on, the other one would be closed. If you don't choose soon, then we would do it on our end.

**Comment by nikhil25803** [comment]
> @nikhil25803 please be more descriptive about what you plan to add in the documentation section for STL

I want to add a readme file that contains the explanation, content and use of STL components like containers, iterators, algorithms, function objects, and allocators.

**Comment by n4i9kita** [comment]
Pick one.
Mention a proper plan. 
I think, we don't need to talk about plagiarism, and its consequences.
I hope you'd be able to write in proper English.
Start with containers, and before I assign you this issue, I need a proper plan. 

1. Which container?
2. What all you will write in a container description?
3. Functions in a container that you'd explain.
4. What are the resources that you'd be using to write the README.

**Comment by n4i9kita** [comment]
@nikhil25803 Vector it is in your case right now.

**Comment by nikhil25803** [comment]
Vectors files are already added in the containers folder.
I want to make a readme file for STL which will have the following elements : 
1. Will start with containers as most of its files are already there so that it will be easy for the reader to understand and implement the code.
2. In containers I will describe Vector, Set, and List.
3. When to use them and how to implement them in a function.
4. YouTube/GeeksForGeeks/StackOverflow are the platforms I will use as a resource, but neither the codes nor the language will be copied from any of these platforms.
5. I will try to describe in the best possible way.

**Comment by nikhil25803** [comment]
Thank You.
Can I have your LinkedIn or Discord ID where I can DM you in case I have to ask for something from you and can keep you updated with my work?

**Comment by n4i9kita** [comment]
For reference - [here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md)
And, when you will provide us with what you have written, we will review it word by word, and ask for changes as per need. So, be prepared mentally.

**Comment by n4i9kita** [comment]
@nikhil25803 you have been asssigned your other issue. Finish it soon, and send a pr for that, and then work on this. If someone else comes then they would be allowed to work on it, otherwise.

**Comment by Lakhankumawat** [comment]
Hey @nikhil25803  , You can only create one issue at a time . I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.

Don't worry you can reopen this issue again once you have opened PR for your existing issue

**Comment by nikhil25803** [comment]
Hey @Lakhankumawat, I have opened the PR for my existing issue #182 
Can you please assign me this issue now so that I can start working on it?
