### ISSUE TITLE
Reverse a Doubly Linked List 

### ISSUE THREAD

**Issue by Pragati1122** [Lakhankumawat/LearnCPP#185]
### Description

The problem is to reverse a doubly linked list. I will be explaining and writing the code to reverse a doubly linked list with a time complexity of O(n) and a constant space complexity. The method is to swap the values of the previous and next pointers of each node in the doubly linked list. I will be explaining the same.
I am a participant at GSSoC'22. 
@Lakhankumawat I want to work on this issue, can you please assign this to me?

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Anand-Anurag** [comment]
I can solve this issue in O(n) tine and O(1) space, Please assign thos issue to me @Lakhankumawat

**Comment by kalash2205** [comment]
please assign me this

**Comment by Pragati1122** [comment]
Please remove this label of no-issue-activity.
