### ISSUE TITLE
Boyer-Moore Voting Algorithm

### ISSUE THREAD

**Issue by michaelehab** [Lakhankumawat/LearnCPP#186]
### Description

The Boyer-Moore voting algorithm is one of the popular optimal algorithms which is used to find the majority element among the given elements that have more than N/ 2 occurrences. 
This works perfectly fine for finding the majority element which takes 2 traversals over the given elements, which works in **O(N) time complexity** and **O(1) space complexity**.
I want to add a popular algorithms problem named: "Majority Element" that uses this algorithm.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
Thank you for a good description but this issue has already been taken up, keep it up and create a new issue
