### ISSUE TITLE
Middle of a given linked list

### ISSUE THREAD

**Issue by nirUpma52** [Lakhankumawat/LearnCPP#187]
### Description

The problem is to find the middle of the linked list .For example, if the given linked list is 1->2->3->4->5 then the output should be 3. 
If there are even nodes, then there would be two middle nodes, we need to print the second middle element. For example, if given linked list is 1->2->3->4->5->6 then the output should be 4. I will write the code using two pointers.
I am a participant at GSSOC'22 .
@Lakhankumawat I want to work on this issue , can u please assign this to me ?

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by kalash2205** [comment]
please assign me this issue

**Comment by aikanshi-1234** [comment]
Please assign this issue to me, and I can add time complexities, space complexities, algorithm, brute force approach, and the optimal solution to this problem.

**Comment by Lakhankumawat** [comment]
This issue will be assigned to @nirUpma52  beacause he came up with issue first .

**Comment by Lakhankumawat** [comment]
For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.
