### ISSUE TITLE
Bipartite Graph

### ISSUE THREAD

**Issue by Mrjoy832** [Lakhankumawat/LearnCPP#188]
### Description

**Description**
Hi, I am **TRIDIB BAG**.  I'm a **GSSoC22 participant.**
I want to add algorithm ,approach and code about **Bipartite Graph** in **G-Graphs** file with proper documentation as there is nothing regarding Bipartite Graph . I'm really want to contribute in this important question . 

Can you please assign it to me?

### Domain

CPP

### Type of Contribution

Addition, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by n4i9kita** [comment]
@Mrjoy832 , you can work on this.
In this issue, you are going to implement an algorithm to check whether a graph is Bipartite or not. Send a PR regarding the same. If merged, then you can create a second issue, or in continuation to this issue, to implement documentation part.

**Comment by n4i9kita** [comment]
You will be assigned the issue soon

**Comment by Mrjoy832** [comment]
Hey @n4i9kita  I have created PR#236 kindly check and merge if all are right

**Comment by miraj0507** [comment]
Hello you haven't already been assigned but you merged it, prior assignment

**Comment by Mrjoy832** [comment]
> Hello you haven't already been assigned but you merged it, prior assignment 

Will I have to do anything else on it?
