### ISSUE TITLE
Infix to postfix under stack 

### ISSUE THREAD

**Issue by VaishnaviMandloi** [Lakhankumawat/LearnCPP#195]
### Description

Description

Want to contribute ( GSSOC'22  )

I will add this following  things 

1. Parenthesis Balancing

check that whether the pairs and the orders of “{“, “}”, “(“, “)”, “[“, “]” are correct in expression or not using stack in O(n) time complexity and O (n) auxiliary space.

2. Infix to prefix or postfix conversion

 infix expressions that we use .  Convert them to  prefix or postfix expression so that more understandable by computer by using stack in O(n) time complexity. 

3. To reverse a word or a string
 If input is ' LearnCPP and GSSOC ' than output will ' GSSOC and LearnCPP 'by using stack in O(n) time complexity. 

Please assign this project to me 
Excited to contribute. 

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by VaishnaviMandloi** [comment]
Please assign this to me , really excited to contribute to project under GSSOC'22

**Comment by miraj0507** [comment]
Hello , I will be more than happy to assign you but please work on one single algo and update the title.

**Comment by miraj0507** [comment]
You can work on infix to postfix and update it under the S-Stack folder , kindly do the changes I will assign you the same

**Comment by VaishnaviMandloi** [comment]
@miraj0507 now is it right

**Comment by miraj0507** [comment]
Goood, wish you all the best go ahead .

**Comment by Sakshi-Singh-040** [comment]
i want work on this issue for GSSOC 2022.
