### ISSUE TITLE
Dutch National Flag Algorithm

### ISSUE THREAD

**Issue by Mrjoy832** [Lakhankumawat/LearnCPP#198]
### Description

Hi, I am TRIDIB BAG. I'm a GSSoC22 participant.
I want to add algorithm ,approach and code about Dutch National Flag  in A-Arrays folder with proper documentation as there is nothing regarding it . I'm really want to contribute in this important question .

Can you please assign it to me?

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
I am sorry, it's already assigned.
