### ISSUE TITLE
Sort the linked list 

### ISSUE THREAD

**Issue by DlVYANSH** [Lakhankumawat/LearnCPP#199]
### Description

Given head of the linked list, Sort the linked list in ascending/descending order

I am participating in gssoc'22. please assign this to me

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by VaishnaviMandloi** [comment]
@Lakhankumawat is this issue is still open can I assign this to myself . I want to work on this.
