### ISSUE TITLE
Readme file for linked list 

### ISSUE THREAD

**Issue by DlVYANSH** [Lakhankumawat/LearnCPP#202]
### Description

I will provide description about the linked list and everything in the readme file
please assign this to me i am also participating in the gssoc'22

### Domain

README

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Please descibe your issue in details and also mention in which directory you'll be contributing . Follow the README guidelines as present in official README of the project .
