### ISSUE TITLE
Implementation of queue using array 

### ISSUE THREAD

**Issue by DlVYANSH** [Lakhankumawat/LearnCPP#204]
### Description

I will provide the program to implement the queue using array (every operation of queue i.e. enqueue, dequeue, isempty, isfull etc)

I will provide proper description about the  queue as well as the comments in the code
gssoc'22

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Hey @rutika1823 @DlVYANSH  , You can only create one issue at a time . I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.
