### ISSUE TITLE
Implementation of queue using linked list

### ISSUE THREAD

**Issue by DlVYANSH** [Lakhankumawat/LearnCPP#205]
### Description

Our program will implement the queue using linked list with operation like enque, deque, isempty, isfull, display the queue etc.

gssoc'22
please assign this to me

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Himanshu1808** [comment]
I would like to work on this issue, can you please assign me? I am a GSSOC'22 participant.
Kindly assign me this issue.

**Comment by Lakhankumawat** [comment]
This issue is assigned to @Himanshu1808  , @Himanshu1808  you can start working on the issue .

**Comment by Lakhankumawat** [comment]
For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.
