### ISSUE TITLE
Find all the Subarrays

### ISSUE THREAD

**Issue by aikanshi-1234** [Lakhankumawat/LearnCPP#208]
### Description

 Problem is to  find all the _subarray_ in the array
Given an array write an algorithm to print all the subarrays.

  

![Screenshot (42)](https://user-images.githubusercontent.com/81483787/156309292-f6caccbb-4cec-4ced-887c-071d05b52005.png)

 Algorithm for the following given problem-
1>Traverse the array from start to end.
2>From every index start another loop from I to the end of the array to get all subarray starting from I, keep a variable sum to calculate the sum.
3>For every index in inner loop update sum = sum + array[j]
4>If the sum is equal to the given sum, print the subarray.

### Domain

CPP

### Type of Contribution

feature, adding, documentation, algorithm, and implementation.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.
- 
- I would request that please assign this problem to me 
- Thank you

**Comment by aikanshi-1234** [comment]
This issue is created by me

**Comment by n4i9kita** [comment]
One issue at a time @aikanshi-1234. Pick one, and the other one would be closed right now.

**Comment by aikanshi-1234** [comment]
I will go with subarrays 
Thankyou

**Comment by aikanshboyal** [comment]
I am a contributor under GGSOC '22. Please assign me this issue @n4i9kita

**Comment by miraj0507** [comment]
I have allowed one of your issues, you can proceed with this one once the other is done. for now we need to keep this at hold.
