### ISSUE TITLE
Backtracking-N Queen problem 

### ISSUE THREAD

**Issue by aikanshi-1234** [Lakhankumawat/LearnCPP#209]
### Description

Problem.
It's an interesting problem.
The N -Queen Problem is a puzzle that is solved through Backtracking with the algorithm.

Algorithm for the following problem-

1) Start in the leftmost column

2) If all queens are placed
    return true
3) Try all rows in the current column. 
   Do following for every tried row.
    a) If the queen can be placed safely in this row 
       then mark this [row, column] as part of the 
       solution and recursively check if placing
       queen here leads to a solution.
    b) If placing the queen in [row, column] leads to
       a solution then return true.
    c) If placing queen doesn't lead to a solution then
       unmark this [row, column] (Backtrack) and go to 
       step (a) to try other rows.
3) If all rows have been tried and nothing worked,
   return false to trigger backtracking.

### Domain

CPP

### Type of Contribution

feature, adding, documentation, algorithm, implementation.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.
![backtrackimg](https://user-images.githubusercontent.com/81483787/156309785-710024de-1ad0-4b85-8b60-f5e511f267b4.png)
 I would like to say that please assign this problem to me
Thank You

**Comment by miraj0507** [comment]
Good job, hoping for a great output on the PR side, good presentation

**Comment by aikanshi-1234** [comment]
> Good job, hoping for a great output on the PR side, good presentation

Thank You @miraj0507

**Comment by vai-shali** [comment]
Hi, is anyone working on this issue? If not, can I work on it for gssoc'22?

**Comment by Sakshi-Singh-040** [comment]
I want to work on this issue for GSSOC 2022.

**Comment by vai-shali** [comment]
@miraj0507 can you please assign this issue to me?
