### ISSUE TITLE
Title Updating readme file of sorting algorithm

### ISSUE THREAD

**Issue by gaurangSaraswat-07** [Lakhankumawat/LearnCPP#218]
### Description

Description: The readme file in the subfolder named sorting algorithm is empty, so updating the readme file by writing a description about all the present sorting algorithms and making a generalised template.

### Domain

README

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by gaurangSaraswat-07** [comment]
@Lakhankumawat Recently I created a pull request of adding counting sort to the sortingAlgorithm folder and I was asked to write a description of the algorithm in readme file but there was no certain template and it was empty. So I was thinking of updating it and also write description of every sorting algorithm present already in the folder? So can you please assign me this issue.

**Comment by n4i9kita** [comment]
@gaurangSaraswat-07 I am sorry. I had an  immediate plans and had to go out of town for some work. I have prepared the template, and added the documentation for bubble sort. I will reach back home by tonight. I will push it by morning. 

I am really sorry. 
Just give me some time, then you add the documentation for counting Sort Algorithm.

**Comment by gaurangSaraswat-07** [comment]
@n4i9kita OKk! I will wait and after you will push the template, I will write the description in that particular format.

**Comment by n4i9kita** [comment]
@gaurangSaraswat-07 go on. Add for Counting sort Algorithm.

**Comment by gaurangSaraswat-07** [comment]
> @gaurangSaraswat-07 go on. Add for Counting sort Algorithm.

Done. Thank  you!
