### ISSUE TITLE
Trapping-rain-water problem

### ISSUE THREAD

**Issue by gp919934** [Lakhankumawat/LearnCPP#220]
### Description

Given n non-negative integers representing height of building whose width is 1, compute how much water it is able to trap after raining.
using both brute force approach and stack method.

Please assign me this issue, @Lakhankumawat
I'm Gssoc'22 participant.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Trapping Rain Water Problem #110 already assigned ,  Duplicate , i  would suggest you to come up with something new thanks

**Comment by Lakhankumawat** [comment]
Also from next time please try to describe your Issue in detail.
Make your issue a descriptive one so it is easy for us
mentors to get hold of your contribution and can guide you for further steps.
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk) , thanks.

**Comment by gp919934** [comment]
Hello sir can you check issue #324
