### ISSUE TITLE
Reverse a Singly Linked list.

### ISSUE THREAD

**Issue by svenkat19** [Lakhankumawat/LearnCPP#221]
### Description

I can come up with a simple and easy to understand code to Reverse a Singly Linked List.

Please Assign (GSSOC'22)

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by svenkat19** [comment]
> Hello, Can you please assign this issue to me Under GSSoC so that I can start working on it

Um.. I actually created the issue so that I can do it 😬😬

**Comment by AnishaRoy1** [comment]
Okay Sure .

**Comment by Rahul-Kumar-prog** [comment]
Hy @svenkat19  I Want To Work On It Can You Assign Me Under GSSoC So That I Start Working On It

**Comment by svenkat19** [comment]
Hey, I have already submitted a pull request for this a week ago. Pls unassign yourself

**Comment by Rahul-Kumar-prog** [comment]
@svenkat19 why this issue not showing any assign or something and still showing in issue section

**Comment by svenkat19** [comment]
Well, I created the issue(as a contributor). And here my the thread for my PR: https://github.com/Lakhankumawat/LearnCPP/pull/272#issuecomment-1063642871
