### ISSUE TITLE
Boruvka's Algorithm for Minimum Spanning Tree

### ISSUE THREAD

**Issue by rahulXbarnwal** [Lakhankumawat/LearnCPP#223]
### Description

Boruvka's Algorithm is a way to find a minimum spanning tree — a spanning tree where the sum of edge weights is minimized. It was the first algorithm developed (in 1926) to find MSTs; Otakar Boruvka used it to find the most efficient routing for an electrical grid.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rahulXbarnwal** [comment]
I am a GSSoC'22 participant. I really want to contribute in this issue. Please assign this issue to me @Lakhankumawat

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
