### ISSUE TITLE
Solution for Josephus Problem 

### ISSUE THREAD

**Issue by DhairyaWankhade** [Lakhankumawat/LearnCPP#225]
### Description
**Josephus Problem Statement** :- We are given the natural numbers n and k. All natural numbers from 1 to n are written in a circle. First, count the k-th number starting from the first one and delete it. Then k numbers are counted starting from the next one and the k-th one is removed again, and so on. The process stops when one number remains. It is required to find the last number.

We can also understand it by following example - 
There are n people standing in a circle waiting to be executed. The counting out begins at some point in the circle and proceeds around the circle in a fixed direction. In each step, a certain number of people are skipped and the next person is executed. The elimination proceeds around the circle (which is becoming smaller and smaller as the executed people are removed), until only the last person remains, who is given freedom. Given the total number of persons n and a number k which indicates that k-1 persons are skipped and kth person is killed in circle. The task is to choose the place in the initial circle so that you are the last one remaining and so survive.

For example, if n = 5 and k = 2, then the safe position is 3. Firstly, the person at position 2 is killed, then person at position 4 is killed, then person at position 1 is killed. Finally, the person at position 5 is killed. So the person at position 3 survives. 

I will provide the Solution for Josephus Problem with best possible time complexity & proper explanation in comments.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
Hello, you need to explain the problem as well and present it so that your chances increse.

**Comment by Abhilasha-Jairath** [comment]
https://github.com/Lakhankumawat/LearnCPP/issues/227

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
