### ISSUE TITLE
Implementation of double link list.

### ISSUE THREAD

**Issue by AnishaRoy1** [Lakhankumawat/LearnCPP#226]
### Description

The program will implement the double link list with operation like insert, check empty, delete, count, search, reverse, display the double link list etc.

I will provide proper description about the double ended link list as well as the comments in the code.

gssoc'22
please assign this to me.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by n4i9kita** [comment]
@AnishaRoy1 you can create just one issue at a time.
 Until an issue has been resolved, closed or merged, you cannot create another issue.
