### ISSUE TITLE
implementation of the circular link list

### ISSUE THREAD

**Issue by AnishaRoy1** [Lakhankumawat/LearnCPP#227]
### Description

The program will implement the circular link list with operation like insert, check empty, delete, count, search, display the circular link list etc.

I will provide proper description about the circular link list as well as the comments in the code.

gssoc'22
please assign this to me.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?

**Comment by ronitrangwani** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?

**Comment by AnishaRoy1** [comment]
I have already been assigned this issue.
