### ISSUE TITLE
implementation of the double circular link list

### ISSUE THREAD

**Issue by AnishaRoy1** [Lakhankumawat/LearnCPP#228]
### Description

The program will implement the double ended circular link list with operation like insert, check empty, delete, count, search, display the double ended circular link list etc.

I will provide proper description about the double ended circular link list as well as the comments in the code.

gssoc'22
please assign this to me.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Purvak-10** [comment]
I would like to work on this, please assign this to me.
