### ISSUE TITLE
Implementation of Shell Sort

### ISSUE THREAD

**Issue by YasmeenKararty** [Lakhankumawat/LearnCPP#231]
### Description

ShellSort is a variation of Insertion Sort. In insertion sort, we move elements only one position ahead. When an element has to be moved far ahead, many movements are involved. The idea of shell sort is to allow the exchange of far items.
@miraj0507 will you please assign this issue to me ?
I am GSSoC 2022 Participant.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?
