### ISSUE TITLE
Longest Increasing Subsequence - O(n)

### ISSUE THREAD

**Issue by Rishi838** [Lakhankumawat/LearnCPP#232]
### Description

The program will tell how to find longest increasing subsequence in an array with both recursive as well as dynamic programming approach.
I will provide proper description about the logic of the program using comments in the code.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
I can assign you the same if you are able to do it in O(N) time, also kindly explain the problem statement, See more presentable it looks, the higher and faster your issues will get accepted.
so please update the title as Longest Increasing Subsequence - O(n)

**Comment by Rishi838** [comment]
yes sir i'll do it in o(n) time with proper comments that will explain the  logic of the program

**Comment by Bhavneet345** [comment]
I would like to work on it under Gssoc22 @iamgunjan @miraj0507, kindly assign me this issue as I have worked on this problem before and can solve it in O(N) time.
