### ISSUE TITLE
OOPS -  contructors and destructors

### ISSUE THREAD

**Issue by kalash2205** [Lakhankumawat/LearnCPP#239]
### Description

C++ is an object oriented language so we should be familiar with oops concept at least the basics of it. 
I would include the basics of oops like classes and contructors, default, parameterized, copy contructors, destructors, etc . 
I would make a class and make a function of all these things inside the class and in the main program demonstrate their uses.

please assign me this issue

thanks
gssoc '22 contributor

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
@kalash2205 please maintain less commits at a time and do not make a mess beacuse then it will be difficult for mentors to review your PR

**Comment by Lakhankumawat** [comment]
Hey @kalash2205  , make your issue a descriptive one so it is easy for us
mentors to get hold of your contribution and can guide you for further steps.
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk) , thanks.

**Comment by miraj0507** [comment]
Kindly update the title and let's be more specific , per issue, so just work on constructors this issue, you can add copy constructors etc etc. per issue be specific, kindly do the changes in the title

**Comment by Lakhankumawat** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by miraj0507** [comment]
OOPs-Constructors

**Comment by kalash2205** [comment]
> @kalash2205 please maintain less commits at a time and do not make a mess beacuse then it will be difficult for mentors to review your PR

@Lakhankumawat i havent made any commits at the moment but i will keep that in mind

**Comment by kalash2205** [comment]
> Hey @kalash2205 , make your issue a descriptive one so it is easy for us mentors to get hold of your contribution and can guide you for further steps. I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk) , thanks.

@Lakhankumawat i wanted to make a class in which i would include all the functions like contructor function, get, set, etc.

**Comment by Lakhankumawat** [comment]
> > @kalash2205 please maintain less commits at a time and do not make a mess beacuse then it will be difficult for mentors to review your PR
> 
> @Lakhankumawat i havent made any commits at the moment but i will keep that in mind

Delete fork and commit while maintaining a clean fork

**Comment by Lakhankumawat** [comment]
> > Hey @kalash2205 , make your issue a descriptive one so it is easy for us mentors to get hold of your contribution and can guide you for further steps. I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk) , thanks.
> 
> @Lakhankumawat i wanted to make a class in which i would include all the functions like contructor function, get, set, etc.

Mention details in issue description not in comments

**Comment by kalash2205** [comment]
> > > @kalash2205 please maintain less commits at a time and do not make a mess beacuse then it will be difficult for mentors to review your PR
> > 
> > 
> > @Lakhankumawat i havent made any commits at the moment but i will keep that in mind
> 
> Delete fork and commit while maintaining a clean fork

sir i havent forked it yet

**Comment by kalash2205** [comment]
> > > Hey @kalash2205 , make your issue a descriptive one so it is easy for us mentors to get hold of your contribution and can guide you for further steps. I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk) , thanks.
> > 
> > 
> > @Lakhankumawat i wanted to make a class in which i would include all the functions like contructor function, get, set, etc.
> 
> Mention details in issue description not in comments

sure thing sir

**Comment by kalash2205** [comment]
@Lakhankumawat sir so right now i should on contructors and getters and setters right? anything else you would like to add or change
