### ISSUE TITLE
 Basic and medium level question program code of linked list

### ISSUE THREAD

**Issue by yaman-694** [Lakhankumawat/LearnCPP#241]
### Description

GSSOC'22 contributor

I want to add solution of linked list question level basic and medium.

please assign me this issue.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Only General Problem Statements are allowed in the repo , please describe your issue or it will be closed .
Linked List is already implemented in the REPO , come up with something new and we will be happy to accept your issue .
