### ISSUE TITLE
Array basics concepts like array rotations, reversal algorithms, rearrangements and order statistics

### ISSUE THREAD

**Issue by Rashmisingh-18** [Lakhankumawat/LearnCPP#249]
### Description

This includes some questions of array rotations, reversal algorithms, rearrangements and order statistics

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Rashmisingh-18** [comment]
Please assign this issue to me, @Lakhankumawat

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?
