### ISSUE TITLE
Number Theory Algorithms

### ISSUE THREAD

**Issue by Rashmisingh-18** [Lakhankumawat/LearnCPP#250]
### Description

This includes number theory algorithms like Euclid GCD, Prime number, Sieve of Eratosthenes and Modulo Arithmetics.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Rashmisingh-18** [comment]
Please assign this issue to me, @Lakhankumawat

**Comment by Nanzzie** [comment]
I want to contribute to this problem sir please assign this issue to me @Lakhankumawat

**Comment by Lakhankumawat** [comment]
@Nanzzie   You can only work on one issue at a time . I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.

**Comment by Lakhankumawat** [comment]
@Rashmisingh-18  You can only work on one algorithm or problem statement in one issue at a time . I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.

**Comment by Rashmisingh-18** [comment]
I want to work on Sieve of Eratosthenes, please assign this issue to me @Lakhankumawat

**Comment by n4i9kita** [comment]
@Rashmisingh-18 check the issues properly. Some else working on the same.
