### ISSUE TITLE
Kadane's Algorithm 

### ISSUE THREAD

**Issue by naugsss** [Lakhankumawat/LearnCPP#259]
### Description

Kadane's Algorithm is a more optimized technique of PREFIX SUM which is used in competitive programming and problem solving.
Using this technique will help us to reduce the time complexity of an algorithm.

I want to add this technique and provide a detailed code with explanation, So please assign me this issue 

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Anuragkr07** [comment]
I want to work on this issue under gssoc 22

**Comment by KhushiRana2003** [comment]
Please assign this to me I am gssoc participant and want to work on this issue.. As I have already solved this problem
