### ISSUE TITLE
Library Management System - Doubly Linked List

### ISSUE THREAD

**Issue by sejalc22** [Lakhankumawat/LearnCPP#262]
### Description

Library Management System shall maintain various linked lists:
&emsp; The Inventory
&emsp; Issue List
&emsp; Waiting List
Features:
&emsp; Add record of new book to inventory
&emsp; Delete record of book from inventory
&emsp; Display inventory
&emsp; Issue copy of a book to student
&emsp; Accept returned copy of a book from student
&emsp; Display Issue List
&emsp; Display Waiting List
&emsp; Display student information from Issue List
&emsp; Display list of students who have issued copies of a particular book

Respective time complexities and comments will be included.

GSSOC'22
Please assign this to me.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Hey @sejalc22  thanks for your interest and suggestion for LearnCPP , but we do not welcome small , medium or large size projects written in C++ , all we want from contributors is Algorithms , Data Structures and General Problem Statements , Your idea is nice though but we won't be able to proceed with you at the moment , thanks .

**Comment by Lakhankumawat** [comment]
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.
