### ISSUE TITLE
LRU Cache 

### ISSUE THREAD

**Issue by Mrjoy832** [Lakhankumawat/LearnCPP#264]
### Description

Hi, I am **TRIDIB BAG**. I'm a GSSoC22 participant.
I want to add algorithm ,approach and code about **LRU Cache in L-LinkedList folder** with proper documentation including proper explanation and code  as there is nothing regarding it . I'm really want to contribute in this important question .

Can you please assign it to me?

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
I will allow you to do so, provided you explain LRU cache well, go for it, On the other side we will evaluate your code.
