### ISSUE TITLE
0/1 Knapsack problem - Subset Sum Problem

### ISSUE THREAD

**Issue by Anuragkr07** [Lakhankumawat/LearnCPP#265]
### Description

I want to add a 0/1 Knapsack application problem using the top-down approach in the Dynamic Programming Folder
Problem:
**Subset Sum Problem**

Problem Description:

In this problem, we will be given a set of non-negative integers and a value sum. We have to determine if there is a subset of the given set with a sum equal to the given sum. 
I will solve this using dynamic programming.

Example:
Input: set[] = {3, 30, 4, 15, 5, 2}, sum = 9
Output: True  
There is a subset (4, 5) with sum 9.

Input: set[] = {3, 34, 4, 11, 5, 2}, sum = 30
Output: False
There is no subset that add up to 30

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Anuragkr07** [comment]
I want to work on this issue as a part of GSSOC'22

**Comment by miraj0507** [comment]
Kindly just work on a single question, as per the rules I cant allow you to do all of them in a single issue so please update the title and I will assign it to you.

**Comment by Anuragkr07** [comment]
> Kindly just work on a single question, as per the rules I cant allow you to do all of them in a single issue so please update the title and I will assign it to you.

okay I have made the changes

**Comment by Anuragkr07** [comment]
I have added a description
