### ISSUE TITLE
 Finding All the Articulation Points in a Graph

### ISSUE THREAD

**Issue by ankitashaw514** [Lakhankumawat/LearnCPP#267]
### Description

I want to Implement an Algorithm to find all the Articulation Points (single points whose failure would split the network into 2 or more components) in a given Graph.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by ankitashaw514** [comment]
I would like to work on this issue under Gssoc22.

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?
