### ISSUE TITLE
LCA of a Binary tree

### ISSUE THREAD

**Issue by stutimohta20** [Lakhankumawat/LearnCPP#268]
### Description

Lowest Common Ancestor of a binary tree using cpp

### Domain

Data Structure

### Type of Contribution

Documentation

### Code of Conduct

- [ ] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by stutimohta20** [comment]
I would like to work on this issue under GSSOC'22

**Comment by TanyaChhikara** [comment]
*Greetings!*
As the issue has not yet been worked upon, I would like to work on it. Kindly assign this issue to me under GSSOC 2022.

**Comment by TanyaChhikara** [comment]
??
