### ISSUE TITLE
H-Heaps

### ISSUE THREAD

**Issue by Lakhankumawat** [Lakhankumawat/LearnCPP#27]
Challanges
- Min Heap with insertion deletion
- Max Heap with inserion deletion
- Heap Sort 
- Heapify

You are allowed to make separate files if you want to make a concise contribution.

**Comment by officSatyam** [comment]
Hey, I am satyam and I want to work on this. Can u please allot me this?

**Comment by Lakhankumawat** [comment]
please follow [**Contributing**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) and [**Algorithms**](https://github.com/Lakhankumawat/LearnCPP#algorithms) Guidelines , your submission must match these
