### ISSUE TITLE
Top view of a binary tree

### ISSUE THREAD

**Issue by Chahat-M** [Lakhankumawat/LearnCPP#271]
### Description

I wish to add a new folder of View of a binary tree under T-Tree and add top view and bottom view cpp files. The new folder structure would look like this - 
```
LearnCPP
    |-- T - Tree
       |-- B-Binary Search
       |-- T-TreeTraversal
       |-- B- Binary Tree View 
           |-- Top View
           |-- Bottom View
```
Please assign me this issue under GSSoC'22

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
kindly update the title as you can just work with one view, You may select which one, as soon as you update I will give you the access

**Comment by Chahat-M** [comment]
Done.

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?
