### ISSUE TITLE
add algorithm to count nodes at a particular level in a tree.

### ISSUE THREAD

**Issue by shreyasharma0201** [Lakhankumawat/LearnCPP#273]
### Description

Add algorithm to count nodes at a particular in a tree.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by arzitmahajan** [comment]
Hey Please Assign me this work (GSSOC 2022)
