### ISSUE TITLE
OOP concept (Polymorphism)

### ISSUE THREAD

**Issue by AmanSarraf** [Lakhankumawat/LearnCPP#276]
### Description

I want to add a brief explanation and sample code for explaining the complete polymorphism concept, under Gssoc'22.

### Domain

CPP

### Type of Contribution

Addition, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
make sure you do it under O-oops folder

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?

**Comment by AmanSarraf** [comment]
done
