### ISSUE TITLE
Roman to Integer

### ISSUE THREAD

**Issue by Ishika2** [Lakhankumawat/LearnCPP#290]
### Description

Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.

Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
For example, 2 is written as II in Roman numeral, just two one's added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written from largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:

I can be placed before V (5) and X (10) to make 4 and 9. 
X can be placed before L (50) and C (100) to make 40 and 90. 
C can be placed before D (500) and M (1000) to make 400 and 900.

Given a roman numeral, convert it to an integer.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Ishika2** [comment]
Hey @Lakhankumawat @officSatyam @n4i9kita @ujjwalban ,
I want to implement the data structure - Hash Table by solving the above question. So please assign this issue to me.
I am a GSSoC'22 contributor, so please add the required labels too, I would be very thankful to you.
Thanks and Regards
Ishika Punchariya

**Comment by Lakhankumawat** [comment]
Hi @Ishika2  thanks for your contribution but problem statements are not allowed in the REPO , only generalised problem statements are allowed like , Travelling Salesman Problem , N-Queen Problem and similar problems

**Comment by Lakhankumawat** [comment]
Hey @Ishika2  , You can only work on one issue at a time . I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.

**Comment by Ishika2** [comment]
> Hey @Ishika2 , You can only work on one issue at a time . I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.

Oh okay, sorry for that.
