### ISSUE TITLE
1D Peak in an array

### ISSUE THREAD

**Issue by Mitternachtsmond** [Lakhankumawat/LearnCPP#294]
### Description

I would like to add an algorithm to find 1D peak in an array.
I would add it in A-Array folder

1D peak in an array is element which is greater than both of its adjacent elements and in case of corner elements it is greater than the only adjacent element.

@Lucifer4255 @ujjwalban Please assign me this issue

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rashita79** [comment]
I am also ready to get this task

**Comment by Mitternachtsmond** [comment]
@rashita79 Could you please choose another issue.
It's a small algorithm which can be done by a single perosn

**Comment by gaurijoshi22** [comment]
Can I contribute to this project??
