### ISSUE TITLE
Longest common prefix

### ISSUE THREAD

**Issue by rashita79** [Lakhankumawat/LearnCPP#300]
### Description

strings question gssoc 2022
i want to add this too

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rashita79** [comment]
@Lakhankumawat I can do this using 5 approch , assign me

**Comment by Lakhankumawat** [comment]
@rashita79  you can work on this issue but make sure that this thing is not present in Repo before making a pull request .
