### ISSUE TITLE
Add code for AVL tree 

### ISSUE THREAD

**Issue by horosahil** [Lakhankumawat/LearnCPP#301]
### Description

Description
AVL tree is a self-balancing Binary Search Tree (BST) where the difference between heights of left and right subtrees cannot be more than one for all nodes. 
Time complexity:
insert : O(logn)
delete : O(logn)
search : O(logn)

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?
