### ISSUE TITLE
Binary Tree details

### ISSUE THREAD

**Issue by Purvak-10** [Lakhankumawat/LearnCPP#302]
### Description

I would like to add an algorithm to find 
 1. Number of leaf nodes in the binary tree
 2. Number of Internal nodes in the binary tree
 3. Total number of nodes in the binary tree
 4. Height of the binary tree

@Lucifer4255 @ujjwalban Please assign me this issue

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Dharmesh177** [comment]
I want to work on this issue. please assign it to me

**Comment by Purvak-10** [comment]
Umm… Actually I came first bro

**Comment by Purvak-10** [comment]
> I want to work on this issue. please assign it to me
> @Lucifer4255 @ujjwalban Please assign me this issue

Umm… Actually I came first bro
