### ISSUE TITLE
Level Order Traversal 

### ISSUE THREAD

**Issue by arzitmahajan** [Lakhankumawat/LearnCPP#306]
### Description

Code of Printing Node's data of binary tree at each level (O(N) Time complexity and O(N) Space Complexity

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by arzitmahajan** [comment]
Level Order Traversal

**Comment by arshkhatwani** [comment]
I want to contribute to this issue as part of GSSOC 22, kindly assign me as soon as possible, please.

**Comment by arshkhatwani** [comment]
\assign

**Comment by KhushiRana2003** [comment]
Please assign this to me I am gssoc participant and want to work on this issue.. As I have already solved this problem
