### ISSUE TITLE
Title Reverse LinkedList (without using extra space)

### ISSUE THREAD

**Issue by SoumyoNathTripathy** [Lakhankumawat/LearnCPP#308]
### Description

Given the head of a singly linked list and two integers left and right where left <= right, reverse the nodes of the list from position left to position right, and return the reversed list.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Bhavneet345** [comment]
I want to contribute to this task, kindly assign me as soon as possible
