### ISSUE TITLE
Left rotate an array by one

### ISSUE THREAD

**Issue by mehakk-Bhatia** [Lakhankumawat/LearnCPP#317]
### Description

Hello ! 
I am GSSOC '22 contributor.
In this problem we need to left  rotate the array by 1 place.
for example: 
I/P :  {10 , 20 , 30 , 40}
O/P:  {20 , 30 , 40 , 10}

### Domain

Data Structure

### Type of Contribution

Addition, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Bhavneet345** [comment]
I want to contribute to this task, kindly assign me as soon as possible

**Comment by Bhavneet345** [comment]
I would like to work on it under Gssoc22 @iamgunjan @miraj0507

**Comment by mehakk-Bhatia** [comment]
i have created this issue , so i want to work on it under GSSOC 22 . please assign this issue to me . @miraj0507
