### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by Abd-ELrahmanHamza** [Lakhankumawat/LearnCPP#320]
### Description

Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.

A subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.

For example, "ace" is a subsequence of "abcde".
A common subsequence of two strings is a subsequence that is common to both strings.
I will solve it using dynamic programming.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by arshkhatwani** [comment]
I want to contribute to this issue, kindly assign me as soon as possible, please.
