### ISSUE TITLE
Knuth–Morris–Pratt Algorithm

### ISSUE THREAD

**Issue by BabyElias** [Lakhankumawat/LearnCPP#321]
### Description

I would like to add KMP Algorithm to the folder String Algorithms.It is the most optimal pattern searching algorithm used in string-matching. While most pattern searching algorithms have a time complexity of O(n^2),this performs the task in O(n).

I am a GSSoC Contributor.
Please assign me this issue.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Sakshi-209** [comment]
please assign me this issue under gssoc'22
