### ISSUE TITLE
The Celebrity Problem

### ISSUE THREAD

**Issue by gp919934** [Lakhankumawat/LearnCPP#324]
### Description

There are N people at the party out of which one of them is a celebrity. Celebrity does not any of the remaining N-1 people, but all of them know Celebrity. You are given a matrix of who knows who. find the celebrity.
I will provide enough explanation of this question using both brute-force and its optimized approach. 

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by KhushiRana2003** [comment]
Please assign this to me I am gssoc participant and want to work on this issue.. As I have already solved this problem

**Comment by gp919934** [comment]
> Please assign this to me I am gssoc participant and want to work on this issue.. As I have already solved this problem

sorry I had already completed this issue .
