### ISSUE TITLE
Lcm and gcd calculator

### ISSUE THREAD

**Issue by gaurijoshi22** [Lakhankumawat/LearnCPP#332]
### Description

Description: we can add the feature of gcd and lcm calculation in calculator using cpp. This uses the method of Euclid's algorithm.  I am gssoc'22 contributor. 

Please assign me this task @la

### Domain

ALGORITHM

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miretteamin** [comment]
Hii!
I am a participant in GSSOC'22. Can you please assign me this issue.
I've implemented a lot of algorithms and participated in many competitions.
Thank You.
