### ISSUE TITLE
To store student data using classes

### ISSUE THREAD

**Issue by Garvit-Gandhi** [Lakhankumawat/LearnCPP#344]
### Description

I can make a program showing how to make a class and its data members to store student data such as name, roll number, section. This program is a good example for introduction to classes and object oriented programming.
 
### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Bhavneet345** [comment]
I want to contribute to this issue, kindly assign me as soon as possible, please.

**Comment by arsh-opsfuse** [comment]
I want to contribute to this issue, kindly assign me as soon as possible, please.

**Comment by arshkhatwani** [comment]
I want to contribute to this issue, kindly assign me as soon as possible, please.

**Comment by Sakshi-209** [comment]
hey!
please assign me this issue under gsoc'22
thanks

**Comment by Hend123** [comment]
I'm interested in working on this issue. Can you please assign it to me?
