### ISSUE TITLE
Check whether number is power of n 

### ISSUE THREAD

**Issue by shivam-s16** [Lakhankumawat/LearnCPP#346]
### Description

I want to put this into mathematical part that whether a given number m is power of other number n . If no the lowest number then m which is power of n.

let m = 32 and n= 3 then it will result in no and 27 
and if m = 64 and n= 4 then it result in yes. 

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by MohamedRadyA** [comment]
\assign

**Comment by Lakhankumawat** [comment]
@shivam-s16  you can work on this issue buddy
