### ISSUE TITLE
Check if a string is subsequence of another string

### ISSUE THREAD

**Issue by Anuragkr07** [Lakhankumawat/LearnCPP#348]
### Description

Problem:
Given Strings A and B. We have to find if string B is a subsequence of String A.

Example 1:

Input :
A: abcde
B: ace

Output:
True

Example 1:

Input :
A: abcde
B: aec

Output:
False

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Anuragkr07** [comment]
Please allow me to work on this issue as a part of GSSoc'22

**Comment by KhushiRana2003** [comment]
Please assign this to me I am gssoc participant and want to work on this issue.. As I have already solved this problem
