### ISSUE TITLE
Maximum Path Sum Between Two Leaves

### ISSUE THREAD

**Issue by Bhavneet345** [Lakhankumawat/LearnCPP#354]
### Description

We are given a non-empty binary tree where each node has a non-negative integer value. We need to return the maximum possible sum of path between any two leaves of the given tree.
The path is also inclusive of the leaf nodes and the maximum path sum may or may not go through the root of the given tree.
If there is only one leaf node in the tree, then we have to return -1.

INPUT TREE - 
![binarytree2-5129](https://user-images.githubusercontent.com/84433782/156821838-cf24280a-38f8-4340-82dc-4caa5f81cf11.png)

OUTPUT - 
The paths between the leaves are as follows :
(1). 9->4->7               (sum = 20)
(2). 9->4->6->3            (sum = 22)
(3). 9->4->6->5->2         (sum = 26)
(4). 7->4->6->3            (sum = 20)
(5). 7->4->6->5->2         (sum = 24)
(6). 3->6->5->2            (sum = 16)

Out of all the above 6 paths, path 9->4->6->5->3 is the maximum sum path with the sum 26.

@ujjwalban @n4i9kita kindly assign this task to me as I will be able to provide an optimized solution for the problem statement given.
Thank You ,
GSSOC'22

### Domain

Data Structure

### Type of Contribution

Addition, Refactoring, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by arshkhatwani** [comment]
I want to contribute to this issue, kindly assign me as soon as possible, please.
