### ISSUE TITLE
Merge two sorted linked lists

### ISSUE THREAD

**Issue by nirUpma52** [Lakhankumawat/LearnCPP#356]
### Description

Description : 
L-Linked list 
Write a SortedMerge() function that takes two lists, each of which is sorted in increasing order, and merges the two together into one list which is in increasing order. SortedMerge() should return the new list. The new list should be made by splicing together the nodes of the first two lists.

For example if the first linked list a is 5->10->15 and the other linked list b is 2->3->20, then SortedMerge() should return a pointer to the head node of the merged list 2->3->5->10->15->20. I will write the code using recursion. 
I am a participant at GSSOC'22. 
@Lakhankumawat  I want to work on this issue,  can u please assign this to me?

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by andrew9078** [comment]
Hi! I'm interested on working on this issue, can you assign it to me?
