### ISSUE TITLE
Pascal's Triangle 

### ISSUE THREAD

**Issue by SiddhantPawar03** [Lakhankumawat/LearnCPP#358]
### Description

Pascal's triangle is an array of binomial coefficients. The numbers in Pascals triangle are placed in such a way that each number is the sum of two numbers just above the number. Pascal's triangle is used widely in probability theory, combinatorics, and algebra.

The value of n th entry in line number line is C(line, n). The value can be calculated using following formula:
C(line, n)   = line! / ( (line-n)! * n! )

I'm a GSSOC'22 Participant please assign me this issue. Hoping to contribute further!

### Domain

Standard Template Library

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by navyasharma0203** [comment]
Could you please assign the level tag to this issue??
