### ISSUE TITLE
Insertion Sort in Linked List

### ISSUE THREAD

**Issue by Bhavneet345** [Lakhankumawat/LearnCPP#359]
### Description

I want to contribute to the LearnCPP project by implementing Insertion Sort Algorithm using Linked List Data Structure.
For Example - 
I/P - 4 2 1 3 -1 (-1 indicates the end of the Linked List)
O/P - 1 2 3 4
I am a participant at GSSOC'22.
@Lakhankumawat Please assign me this problem as I really want to work on this issue.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Bhavneet345** [comment]
I would like to work on it under Gssoc22 @iamgunjan @miraj0507, kindly assign me this issue.

**Comment by Hend123** [comment]
Please assign it to me under GSSOC22 . I want to work on this issue

**Comment by Bhavneet345** [comment]
I have raised this issue so I would like to go forward with it

**Comment by Hend123** [comment]
What do you mean, you want this issue ? or assign it to me

**Comment by Bhavneet345** [comment]
Yes I raised this issue and I would like to work on it
