### ISSUE TITLE
Dijkstra’s Algorithm 

### ISSUE THREAD

**Issue by SiddhantPawar03** [Lakhankumawat/LearnCPP#361]
### Description

Description:
 It is an algorithm for finding the shortest paths between nodes in a graph.
Dijkstra's Algorithm works on the basis that any subpath Y -> Z of the shortest path X -> Z between vertices X and Z is also the shortest path between vertices Y and Z.
Djikstra used this property in the opposite direction. The algorithm uses a greedy approach in the sense that we find the next best solution hoping that the end result is the best solution for the whole problem.

I'm a GSSOC'22 contributor, would like to work on same issue, hope you assign me this issue!

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by arzitmahajan** [comment]
bro use "/assign" otherwise someone else will get your question

**Comment by navyasharma0203** [comment]
Could you please put a Level tag for the above issue

**Comment by navyasharma0203** [comment]
> The assigned contributor has more than 3 open issues, kindly reassign manually (@Supervisors/Mentors)

I can complete the given issue on time....no worries :)
