### ISSUE TITLE
Running Median

### ISSUE THREAD

**Issue by Bhavneet345** [Lakhankumawat/LearnCPP#365]
### Description

I want to contribute a very famous problem of Data Structures and Algorithms named - The Running Median, which focuses on calculating the median for a continuous stream of numbers.

For Example - 
Input -
6  /*total numbers in continous stream */
6 2 1 3 7 5
Ouptut -
6 4 2 2 3 4

Explaination - 
S = {6}, median = 6
S = {6, 2} -> {2, 6}, median = 4
S = {6, 2, 1} -> {1, 2, 6}, median = 2
S = {6, 2, 1, 3} -> {1, 2, 3, 6}, median = 2
S = {6, 2, 1, 3, 7} -> {1, 2, 3, 6, 7}, median = 3
S = {6, 2, 1, 3, 7, 5} -> {1, 2, 3, 5, 6, 7}, median = 4

Note - We have to print only the integer part of the median.

@ujjwalban @miraj0507 Kindly assign this problem to me as a part of the GSSOC'22 contribution.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Bhavneet345** [comment]
@iamgunjan @miraj0507 Kindly assign this issue to me so that I can work on it as soon as possible, Thank you.

**Comment by miraj0507** [comment]
kindly type /assign to self assign it
