### ISSUE TITLE
Linked list with header node

### ISSUE THREAD

**Issue by VaishnaviMandloi** [Lakhankumawat/LearnCPP#367]
### Description

Description 
Header node is a dummy node .present at the beginning of the node may be empty or can be used to contain information. 
The use of header node made the program simple and faster . As it never empty because header is beginning,  so we can drop the  cases where linked list is null.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by SUSHANTDBANSODE** [comment]
Please Assign Me This Under Gssoc'22
