### ISSUE TITLE
Union and intersection of two sorted arrays

### ISSUE THREAD

**Issue by Khushi260** [Lakhankumawat/LearnCPP#368]
### Description

I'm a GSSOC'22 contributor.

Given two arrays a[] and b[] of size n and m respectively. The task is to find union between these two arrays.

- Problem Statement [here](https://practice.geeksforgeeks.org/problems/union-of-two-arrays3538/1)

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Sakshi-209** [comment]
please assign this issue to me under gssoc'22

**Comment by SUSHANTDBANSODE** [comment]
Please Assign Me This Under Gssoc'22

**Comment by Hend123** [comment]
Please assign it to me under GSSOC22. I want to work on this issue

**Comment by Hend123** [comment]
\assign
