### ISSUE TITLE
Implementation of  the Levenshtein distance (Edit distance) Problem using Dynamic programming as a part of GSSOC'22

### ISSUE THREAD

**Issue by salahashraf253** [Lakhankumawat/LearnCPP#375]
### Description

Description
I want to implement the Levenshtein distance (Edit distance) Problem using DP 

The Levenshtein distance (or Edit distance) is a way of quantifying how different two strings are from one another by counting the minimum number of operations required to transform one string into the other.

Example:
Input: text1 = "aabc", text2 = "adbf"
Output: 2

Give me a chance to contribute under GSSOC'22

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by salahashraf253** [comment]
@Lakhankumawat  , kindly check this issue .

**Comment by salahashraf253** [comment]
@Lakhankumawat

**Comment by miretteamin** [comment]
@Lakhankumawat 
Can this issue be assigned to me as no one worked on it? Also I want to implement edit distance problem using dp but the modified one in which u choose cost for insert, delete and replace.
Or can I create a new issue?
Thank you!
