### ISSUE TITLE
Add Line drawing algorithms

### ISSUE THREAD

**Issue by ABHIGPT401** [Lakhankumawat/LearnCPP#377]
### Description

Add line drawing algorithm such as Bresenham.

### Domain

Other

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by ABHIGPT401** [comment]
Please assign me this!

**Comment by santriptmehta** [comment]
please assign this to me  GsSOC
