### ISSUE TITLE
Organise Algorithms

### ISSUE THREAD

**Issue by Lakhankumawat** [Lakhankumawat/LearnCPP#4]
Organise Algorithms in [`Day-100(Algorithms)`](https://github.com/Lakhankumawat/LearnCPP/tree/main/Day-100(Algorithms)) section according to their types .

- Like All the algorithms which are there in Dynamic Programming should be in DP folder.
- All With Greedy approach in G-Greedy folder.
- And with Graphs in their respective folders.

- Add time complexities , space complexities to algorithms .

**Comment by hrishik18** [comment]
I am contribution from hackoberfest2021
Please assign me this!!

**Comment by Lakhankumawat** [comment]
This issue is open for public  - you can go ahead

**Comment by n4i9kita** [comment]
@Lakhankumawat  as I am now working on the second part of my plan. That is, add the readme to each folder. I think you can assign me this task, as this is similar to what I am doing now. 

One issue happened is that, I made folders of 'A-Array' and 'A-AdvancedDataStructures' but it was not pushed. Looking into it.

**Comment by Lakhankumawat** [comment]
Yea empty folders are not pushed , so you add something then they'll be pushed , and you can work on this issue

**Comment by n4i9kita** [comment]
Okay. Thanks
