### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by Mujeeb-shaikh7** [Lakhankumawat/LearnCPP#404]
### Description

It is an algorithm to sort the elements in an ascending order.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Mujeeb-shaikh7** [comment]
'\assign'

**Comment by Hend123** [comment]
Please assign it to me under gssoc 2022. I want to work on this issue

**Comment by dinamaher12** [comment]
\assign

**Comment by MrGladiator14** [comment]
### Hi, I am interested in this issue, can you please assign it to me?

**Comment by HodaTouny** [comment]
\assign
