### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by sushantdbansode** [Lakhankumawat/LearnCPP#406]
Description
I would Like to Add this Standard problem under Arrays Section 

You have been given a random integer array/list(ARR) of size N. Write a function that rotates the given array/list by D elements(towards the left).

Please assign me this Problem Under The name of Gssoc'22 

Domain

CPP

Type of Contribution

Addition

**Comment by SUSHANTDBANSODE** [comment]
'/assign'

**Comment by goyalsaksh** [comment]
Hello , I am a gssoc contributor , please assign this issue to me

**Comment by Lakhankumawat** [comment]
@sushantdbansode  this issue is assigned to you , you can start working on it buddy
