### ISSUE TITLE
C++ code to find out cycle in a linked list.

### ISSUE THREAD

**Issue by rajdip-b** [Lakhankumawat/LearnCPP#415]
## Cycle in linked list

This c++ program will find out whether if the given linked list has self loops or not.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by drkspark** [comment]
Hey! Please assign this issue to me under GSSOC22. I will solve it using Floyd's Slow and Fast pointer method.
Method Description : We use two pointer one slow and one fast. The slow pointer is moved 1 step at a time and fast pointer is moved 2 steps at a time. So if there is a loop, then these pointers will meet a point.
If no loop is there then they won't meet and  the loop gets terminated once the fast pointer value becomes NULL.
Time Complexity : O(N)
Space Complexity : O(1)
And  I will add other methods of solving the same too.

**Comment by rajdip-b** [comment]
Hey @drkspark I opened this issue to solve this  problem. I was going to use the same algorithm. I am absolutely cool with you solving this problem but the only thing is I don't think I can assign this to you im just an ordinary contributor :(

**Comment by drkspark** [comment]
Sorry. I don't know how this works.. This is my first time. I thought it was open to be assigned to anyone. Please go ahead and work on it.😊

**Comment by rajdip-b** [comment]
Well in that case my friend, this repository also gives credit for posting new problems so feel free to put your PR in this issue. I insist. Take this issue; you will be assigned shortly and good luck!

**Comment by dev24il** [comment]
Hello @rajdip-b, I want to contribute in this issue.

**Comment by Mrjoy832** [comment]
@Lakhankumawat , There is a challenge from **Scaler-30-Days-OpenSource** to contribute to any large Size repo, So I have chosen this and want to work on this issue ....I am reopening this issue and going to assign myself.
