### ISSUE TITLE
Static implementation of Stack

### ISSUE THREAD

**Issue by janhavikale06** [Lakhankumawat/LearnCPP#449]
### Description

A stack data structure can be implemented using a one-dimensional array. But stack implemented using array stores only a fixed number of data values. Just define a one dimensional array of specific size and insert or delete the values into that array by using LIFO principle with the help of a variable called 'top'. Initially, the top is set to -1. Whenever we want to insert a value into the stack, increment the top value by one and then insert. Whenever we want to delete a value from the stack, then delete the top value and decrement the top value by one.

Push - This adds a data value to the top of the stack.
Pop - This removes the data value on top of the stack.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by janhavikale06** [comment]
@Lakhankumawat can you please check my issue?

**Comment by Sakshi-Singh-040** [comment]
I want to work on this issue for GSSOC 2022
