### ISSUE TITLE
Quick sort

### ISSUE THREAD

**Issue by 89-manshi** [Lakhankumawat/LearnCPP#450]
### Description

Update the Partition function . Pls assign it to me.

### Domain

CPP

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by KhushiRana2003** [comment]
Please assign this to me.. I have already solved this problem and want to work on this issue..
