### ISSUE TITLE
Searching Algorithms

### ISSUE THREAD

**Issue by isha614** [Lakhankumawat/LearnCPP#451]
### Description

I want to add more searching algorithms with code and documentation like exponential , jump search

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miretteamin** [comment]
Hii!
I am a participant in GSSOC'22. Can you please assign me this issue.
I've implemented a lot of algorithms and participated in many competitions.
Thank You.

**Comment by janhavikale06** [comment]
I want to work on this issue. Can you please assign me?
