### ISSUE TITLE
Floor Value in Binary Search Tree

### ISSUE THREAD

**Issue by Mrjoy832** [Lakhankumawat/LearnCPP#460]
### Description

> Hi, I am **TRIDIB BAG.**  I'm a GSSoC22 participant.
I want to add algorithm ,approach and code calculating **Floor value of a BST** in **learnCPP/T-Tree/B-BinarySearchTree/**  folder with proper documentation including proper explanation and code as there is nothing regarding it . I really want to contribute in this important question .

> Can you please assign it to me?

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Mrjoy832** [comment]
@miraj0507  hey kindly assign it to me ...I am just created issue regarding this question ...will be start working soon ..please assign it to me

**Comment by miraj0507** [comment]
Hey just type /assign you will be assigned the same
