### ISSUE TITLE
Create a Mirror Tree from a given Binary Tree

### ISSUE THREAD

**Issue by sneha2042** [Lakhankumawat/LearnCPP#467]
### Description

We are given a binary tree and the task is to create and print a new binary tree which is a mirror image of the given binary tree.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Kavya-mothukuri** [comment]
Hi ,I would like to work on this can you assign it to me

**Comment by sneha2042** [comment]
.

**Comment by sneha2042** [comment]
up

**Comment by sneha2042** [comment]
.
