### ISSUE TITLE
moore's voting algorithm 

### ISSUE THREAD

**Issue by satyam4484** [Lakhankumawat/LearnCPP#47]
**Programming Paradigm:** Arrays
The boyer-Moore voting algorithm is used to find the majority element by eliminating the non-majority elements.

**Comment by satyam4484** [comment]
I want to add these , could you tell how to get started I don't know much about github

**Comment by Lakhankumawat** [comment]
So there is a meeting link in REPO readme make sure you join that it will be easier for us to guide you better on meet with live interaction , meantime you can follow contribution guidelines and I am assigning this issue to you , you can work on it but make sure you open a pr after 1st March if you are here for points before that you can contribute but you won't get any points , thanks

**Comment by satyam4484** [comment]
ya sure i will make pr after 1 march

**Comment by satyam4484** [comment]
hey can i make pull request as a part of GSSOC

**Comment by satyam4484** [comment]
I am pushing to github it's showing you don't have permission, could you tell me how I can resolve these

**Comment by miraj0507** [comment]
> I am pushing to github it's showing you don't have permission, could you tell me how I can resolve these

Create a forked copy of the repo and then in the designated folder create the changes and request for a pull request

**Comment by satyam4484** [comment]
It is solved
