### ISSUE TITLE
3 Cycle

### ISSUE THREAD

**Issue by Bhavneet345** [Lakhankumawat/LearnCPP#472]
### Description

Problem Statement - Given a graph with N vertices (numbered from 0 to N-1) and M undirected edges, then count the distinct 3-cycles in the graph. A 3-cycle PQR is a cycle in which (P,Q), (Q,R) and (R,P) are connected by an edge.

@Lakhankumawat , @iamgunjan, @miraj0507, please assign me this issue as a part GSSOC'22.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by KhushiRana2003** [comment]
please assign me this issue as a part GSSOC'22 I want to work on this issue..

**Comment by Bhavneet345** [comment]
@KhushiRana2003 I raised the issue so I would like to work on it.

**Comment by MrGladiator14** [comment]
Hi, I am interested in this issue, can you please assign it to me?
