### ISSUE TITLE
Adding “Deletion of a node in BST in BinarySearchTree Folder”

### ISSUE THREAD

**Issue by shivanithorve01** [Lakhankumawat/LearnCPP#48]
In Tree/B-BinarySearchTree Folder, there is code for Creating and inserting node in BST. I want to add program for Deleting node in BST. Will you please assign me this issue ?

**Comment by Lakhankumawat** [comment]
There can be only one issue assigned to a contributor at a time so you can create PR for the issue assigned to you then you can start working on this , meantime close this issue and reopen again when you want to contribute otherwise some else might grab it , thanks .

**Comment by shivanithorve01** [comment]
Okay Thanks

**Comment by shivanithorve01** [comment]
@Lakhankumawat Please assign this issue to me
