### ISSUE TITLE
B-Tree Algorithm in Tree Folder

### ISSUE THREAD

**Issue by ayushi1210** [Lakhankumawat/LearnCPP#51]
B-Tree is a self-balancing search tree. When the number of keys is high, the data is read from disk in the form of blocks. Disk access time is very high compared to the main memory access time. The main idea of using B-Trees is to reduce the number of disk accesses. This is highly used for the data base management and other places where large data is to be stored.
I would like to contribute this with C- Program.
@Lakhankumawat will you please assign this issue to me ?
I'm GSSoC 2022 Participant.

Time Complexity
Search - O(log n)
Insert - O(log n)
Delete - O(log n)

**Comment by Lakhankumawat** [comment]
Also please read this section , it will be helpful [Algorithms](https://github.com/Lakhankumawat/LearnCPP#algorithms)

Coding period starts form 1st March , before that you can contribute but sorry to say you won't get any points.

Thanks for your interest ,
Happy Coding !!
