### ISSUE TITLE
Linked List

### ISSUE THREAD

**Issue by arsh-111** [Lakhankumawat/LearnCPP#53]
Linked list is non-primitive linear data structure. It consist of node, wherein each node consists of two parts : 1) data 2) link to the next node. Types of Linked Lists are singly linked list, doubly linked list, circular singly linked list, circular doubly linked list.
I would like to contribute to this project.
Hello @Lakhankumawat, I am a GSSOC'22 contributor. I am eager to contribute, please consider the issue and assign me with this project. Thank you.

**Comment by Vikash-8090-Yadav** [comment]
@arsh-111  please be more specific, what would you like to contribute?
What are you planning to implement in LInked list?
Or you want to write readme for it?

**Comment by Lakhankumawat** [comment]
If you want to contribute a linked list ,singly linked list, doubly linked list, circular singly linked list, circular doubly linked list. please create a specific issue for that beacuse by including all of those you cover many issues i mean it would be better for you if you create separate issues for each one of them you'll get more points

**Comment by Vikash-8090-Yadav** [comment]
@Lakhankumawat  can i create issue for the singlyLinkedlist .. under **linkedlist** repo
which include basic operatio insert , update , delete , and advance algo also like ...deleting node at the beginning , merge sort and, palindrome and  many more ......

**Comment by arsh-111** [comment]
@Lakhankumawat  I would like to implement operation on singly linked list (insert at begin, insert at end, insert at specific position, delete from begin, delete from specific position, delete from end, traverse), Circular singly linked list (insert at begin, insert at end, insert at specific position, delete from begin, delete from specific position, delete from end, forward traverse, backward traverse)

**Comment by arsh-111** [comment]
@Lakhankumawat  Thank you, i will create an issue.
