### ISSUE TITLE
Flatten a binary tree to linked list 

### ISSUE THREAD

**Issue by shivamtrip-st** [Lakhankumawat/LearnCPP#536]
### Description

here we have  a binary tree and our task is flatten it  into inked list and print .

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Satya-Prakash0** [comment]
I would like to work on this issue , can you assign me !

**Comment by shivamtrip-st** [comment]
> ### Description
> here we have a binary tree and our task is flatten it into inked list and print .
> 
> ### Domain
> Data Structure
> 
> ### Type of Contribution
> Addition
> 
> ### Code of Conduct
> * [x]  I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

/assign
