### ISSUE TITLE
Krishnamurthy Number/Strong Number

### ISSUE THREAD

**Issue by Korak-Sengupta** [Lakhankumawat/LearnCPP#537]
I want to explain, how to find whether a number is Krishnamurthy Number/Strong Number or not in CPP, and to generate all those numbers within a range. Kindly assign this to me

domain: Mathematical Algo

**Comment by Korak-Sengupta** [comment]
> Hello @Korak-Sengupta, thanks for creating your first issue at LearnCPP, hope you followed the guidelines.

yeah have followed

**Comment by Hend123** [comment]
I'm interested in working on this issue. Can you please assign it to me?

**Comment by dinamaher12** [comment]
> /assign
