### ISSUE TITLE
Number Theory 

### ISSUE THREAD

**Issue by Akshat-z** [Lakhankumawat/LearnCPP#545]
### Description

I want to contribute on basic number theory topics like:
1. The prime number using the sieve of Eratosthenes.
2.  GCD
3. Prime Factor
4.  Binary Exponentiation

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Sakshi-209** [comment]
please assign this issue to me under gssoc'22

**Comment by LifelongLearner-HEND** [comment]
\contribute with GCD
