### ISSUE TITLE
Perfect Number

### ISSUE THREAD

**Issue by aparnamittal** [Lakhankumawat/LearnCPP#547]
### Description

A perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself.

Eg:  6 is a positive number that is completely divisible by 1, 2, and 3. We know that the number is also divisible by itself but we will not include it in the addition of divisors. When we add these divisors (1 + 2 + 3 = 6), it gives 6, which is equal to the number that we have chosen. So, we say that 6 is a perfect number.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by KhushiRana2003** [comment]
Please assign this to me I am gssoc participant and want to work on this issue.. As I have already solved this problem

**Comment by aparnamittal** [comment]
@KhushiRana2003  I have already committed my PR for this issue . pls create/search for  new issue.

**Comment by youssefahmedzakaria** [comment]
assign it to me
