### ISSUE TITLE
Lexicographical rank of the string

### ISSUE THREAD

**Issue by riyasingh240601** [Lakhankumawat/LearnCPP#550]
### Description

Finding the rank of the string among all its permutations sorted lexicographically by creating an auxiliary array .

Time complexity: O(n)

Please assign me the issue under GSSOC'22.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Hend123** [comment]
I'm interested in working on this issue. Can you please assign it to me?

**Comment by MrGladiator14** [comment]
### Hi, I am interested in this issue, can you please assign it to me?
