### ISSUE TITLE
Title:Deletion in array

### ISSUE THREAD

**Issue by i-am-aisha** [Lakhankumawat/LearnCPP#553]
### Description

Description:
I would like to add algorithm of deletion in array at given index in array folder with proper comments and will mention best and worst time complexity and space complexity.
the algorithm will be as follows-->
firstly we will store element at given index in a variable and start shifting of elements from given index to last index-1 with the help of for loop as array[i]=array[i+1]. and finally return the stored element at given index i.e. "our deleted element is  'this' ".

### Domain

Data Structure

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Satya-Prakash0** [comment]
I would like to work on this issue ,can you assign me this issue
