### ISSUE TITLE
MathematicalAlgorithms

### ISSUE THREAD

**Issue by Akshat-z** [Lakhankumawat/LearnCPP#572]
### Description

Under Mathematical Algorithms, I want to add how to find the factorial of a large number
which can't be stored inside long int
 but can be solved with the help of an array.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Manik-Aggarwal** [comment]
Please assign it to me under gssoc 2022. I want to work on this issue

**Comment by Hend123** [comment]
I'm interested in working on this issue. Can you please assign it to me?

**Comment by Lakhankumawat** [comment]
@Akshat-z  you can start working on this issue buddy this was your issue it was grabbed by someone else i reassigned it to you again .

**Comment by Akshat-z** [comment]
OK
