### ISSUE TITLE
Left view, Right view, Top view and Bottom view of a Binary tree

### ISSUE THREAD

**Issue by ayushim13** [Lakhankumawat/LearnCPP#580]
### Description

1) Code for Printing the left view of the Binary tree.
2) Code for Printing the right view of the Binary tree.
3) Code for Printing the top view of the Binary tree.
4) Code for Printing the bottom view of the Binary tree.

### Domain

Data Structure

### Type of Contribution

Addition, Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Shivani416** [comment]
@ayushim13 I would like to work on this issue , could you assign it to me?

**Comment by manyac24** [comment]
Hey @ayushim13, I'm interested in working on this issue. Can you please assign it to me?

**Comment by MrGladiator14** [comment]
### Hi, I am interested in this issue, can you please assign it to me?

**Comment by Shatakshi-Choudhary** [comment]
Hey @ayushim13 & @Lakhankumawat , I want to work on this issue. I am a GSSoC'22 contributer. Please assign this issue to me.

**Comment by Diishasing** [comment]
hi @Lakhankumawat please assign it to me

**Comment by sonalee21** [comment]
Hello,
I would like to work on this, please assign it to me.
