### ISSUE TITLE
Floyd’s Cycle Detection Algorithm

### ISSUE THREAD

**Issue by janhavikale06** [Lakhankumawat/LearnCPP#59]
### Description

Floyd's Cycle Detection algorithm is a pointer algorithm that uses only two pointers, which move through the sequence at different speeds. It determine whether the linked list has a cycle or not. First, you keep two pointers of the head node. At each iteration, you move one of the pointers by two steps and the other one by one step If they both meet at some point then we have found a cycle; otherwise, no cycle is present in list.
@Lakhankumawat will you please assign this issue to me ?
I'm GSSoC 2022 Participant.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Your algorithm will reside here  [L-LinkedList](https://github.com/Lakhankumawat/LearnCPP/tree/main/L-LinkedList)
