### ISSUE TITLE
Circular Linked List Implementation

### ISSUE THREAD

**Issue by RajAdwaita** [Lakhankumawat/LearnCPP#593]
### Description

will be performing all the operations including inserting, deleting, inserting at the positions as desired by the user in a circular linked list. All operations will be performed using switch case block.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rutika1823** [comment]
Please assign this to me. I  want to work on this issue under GSSoC'22

**Comment by RajAdwaita** [comment]
I am also working as a contributor

**Comment by RajAdwaita** [comment]
I am also waiting for the confirmation form LearnCPP team to proceed  with the work.
