### ISSUE TITLE
Implementation Karatsuba algorithm for fast multiplication using Divide and Conquer algorithm

### ISSUE THREAD

**Issue by salahashraf253** [Lakhankumawat/LearnCPP#596]
### Description

Description
I will implement Karatsuba algorithm for fast multiplication using Divide and Conquer algorithm.
Give me a chance to contribute under GSSOC'22

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
`LearnCPP/D-DivideAndConquerAlgorithms/KaratsubaAlgorithm.cpp` with `README.md`

**Comment by salahashraf253** [comment]
@Lakhankumawat  check the pr again, please.
