### ISSUE TITLE
implementation of doubly ended queue 

### ISSUE THREAD

**Issue by akritisrivastava2** [Lakhankumawat/LearnCPP#599]
### Description

implementation of doubly ended queue with stl and without stl

### Domain

Data Structure

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Manik-Aggarwal** [comment]
Please assign it to me under GSSOC2022

**Comment by Sakshi-209** [comment]
please assign this issue under gssoc'22

**Comment by Shatakshi-Choudhary** [comment]
Hey @Lakhankumawat, Please assign this issue to me. I am a GSSoC'22 Contributer & I will try my best to resolve the issue.

**Comment by Abdulrahman1890** [comment]
Hi @Lakhankumawat, Please assign this issue to me. I am a GSSoC'22 Contributer
