### ISSUE TITLE
📄README

### ISSUE THREAD

**Issue by Lakhankumawat** [Lakhankumawat/LearnCPP#6]
## Aim
- To add readme to all folders 
## What to include in readme
- Everything that is so far written in folder for e.g if there is [Algorithms](https://github.com/Lakhankumawat/LearnCPP/tree/main/Day-100(Algorithms)) folder then add details to each algorithms .
- Details can be added in form such that link to some documentation of a particular algorithm or some kind of useful information below that algo.
- Refer [README](https://github.com/Lakhankumawat/LearnCPP/blob/main/README.md) to follow styling purposes.
- Make tables in your README too

**Comment by apeksha235** [comment]
Can I work on this?

**Comment by Lakhankumawat** [comment]
Sure go ahead

**Comment by n4i9kita** [comment]
Hi @Lakhankumawat.
Can I work on this?

Also, why have we made a folder named Day-100, and there added the algorithms?
Shouldn't we make folders directly for BackTracking, DP, Graphs, Greedy and so on, and add the algorithms there?

If I am understanding it correctly, then we need to add a readme.md for every 'ds or algo' related folder, to describe the concept, and also what is there (the ds and the problems discussed)  in that dir?

**Comment by Lakhankumawat** [comment]
Yaa actually i made the algorithms folder inside and i had to migrate it to out side where as you said
> Shouldn't we make folders directly for BackTracking, DP, Graphs, Greedy and so on, and add the algorithms there?

Also

>we need to add a readme.md for every 'ds or algo' related folder, to describe the concept, and also what is there (the ds and the problems discussed) in that dir? 

I agree with you and i think you have enough idea , you can go ahead and work on this issue , but commit less at a time and then pr , if you do more number of commits at a time it will be difficult for your valuation .

**Comment by Lakhankumawat** [comment]
Yeah sounds great , but make sure you don't run into any conflicts while merging PR , take your time and do it as you wish .

**Comment by Lakhankumawat** [comment]
Also if I am impressed by your contribution I will try to increase the level of PR through which you can get more points , at the end , so best of lucks .

**Comment by n4i9kita** [comment]
Sure.

**Comment by n4i9kita** [comment]
Please provide feedbacks - [here -> A google doc I have prepared for the same](https://docs.google.com/document/d/1_eguXULrcXuxajHR9vAG8iJh_X_gXtwuVvnlL7QlaRI/edit?usp=sharing)

**Comment by n4i9kita** [comment]
I have been working on main branch till now. 
Considering to move to another branch. @Lakhankumawat recommendations.

**Comment by Lakhankumawat** [comment]
yea, sure you can continue with new branch

**Comment by Anjali-Chaudhary3** [comment]
Can i also contribute here?

**Comment by Lakhankumawat** [comment]
> Can i also contribute here? @Lakhankumawat
Sure but contribute after the meet beacuse some of the things will be discussed tomorrow , find the details inside REPO's README

**Comment by n4i9kita** [comment]
@Anjali-Chaudhary3  if you plan to contribute, then it would be good if we can co-ordinate. It would be better to avoid any form of conflicts.

**Comment by Anjali-Chaudhary3** [comment]
Yes .....why not.....then only the things will come out good

**Comment by n4i9kita** [comment]
@Anjali-Chaudhary3 hope to see you in the meet today. After that, we will decide how to go about it.

**Comment by Anjali-Chaudhary3** [comment]
yes

**Comment by Avik-creator** [comment]
Hey everyone I want to contribute to it so would you like to assign this issue to me. I will learn C++ with this also as I am highly interested it learning C++.

**Comment by DlVYANSH** [comment]
@Lakhankumawat 
Hi!
I am contributor in gssoc'22. Can I contribute to it?
I know c++ and beginner in data structures and algorithms

**Comment by n4i9kita** [comment]
If you really want to learn.
@DlVYANSH the issues that you have raised earlier, have you sent a pr for them? And, have they been reviewed yet?

**Comment by Avik-creator** [comment]
I would like to add in readme what can we do with c++ and why do we need it.

**Comment by DlVYANSH** [comment]
> @DlVYANSH the issues that you have raised earlier, have you sent a PR for them? And, have they been reviewed yet?
> 
> @Avik-creator @DlVYANSH, you have to be specific in what you want to contribute in the README sections.
@n4i9kita Yes ma'am i have sent a pr for the issue and it got reviewed. It got tag of next review needed i have updated the pr yesterday morning itself but it didn't got reviewed yet
.

**Comment by Anjali-Chaudhary3** [comment]
@n4i9kita can I add a readme file for binary search ?
I have started my open source journey under gssoc'22 ( so quite confused )

**Comment by n4i9kita** [comment]
@Anjali-Chaudhary3, You will have to create an issue first. Mention the plan that you will follow, and then we will decide to assign you the issue or not. 
 See [this](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) for reference.

- We would accept only high-quality readme's written in proper English. 
- I think we don't need to talk about plagiarism. 
- You can add algorithm and pseudocode in the readme, but no code.
- I might review it a bit harshly, the sole reason is that we want you all to produce the best possible work. So, if you are prepared, then create a new issue for the same.

**Comment by Anjali-Chaudhary3** [comment]
Yes ,@n4i9kita  can you plz check my first issue I have made for adding the readme for binary search
