### ISSUE TITLE
K-Query with Fenwick Tree 

### ISSUE THREAD

**Issue by uhini0201** [Lakhankumawat/LearnCPP#60]
### Description

I would like to give the approach of K-Query with fenwick tree. Fenwick tree is also called Binary Indexed Tree, and the most common application of fenwick tree is K-Queries . This is a very famous one when someone follows the path of competitive programming. I stumbled upon learning this miraculous thing, so would like to share.

@Lakhankumawat Please assign this issue to me. I am a GSSOC'22 contributor.

### Domain

Data Structures

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Please join meet today more details will be shared there

**Comment by Lakhankumawat** [comment]
Seems like your issue is a bit of dilemma whether to include it in Problem Statement or an algorithm , please explain it a bit more .

**Comment by uhini0201** [comment]
Fenwick tree is widely used in range-query problems and k-query is a very famous application of that algorithm, so basically i would be explaining the working and the algorithm as to visualize fenwick tree without example is hard, so i will be explaining the application of fenwick tree using k-query. @Lakhankumawat

**Comment by uhini0201** [comment]
@Lakhankumawat  please assign me this issue so that i can start working on it.

**Comment by miraj0507** [comment]
It comes under Competitive programming, go ahead.Expecting a good one from you.

**Comment by uhini0201** [comment]
Thank you so much @miraj0507
