### ISSUE TITLE
Doubly linked list 

### ISSUE THREAD

**Issue by joe09222** [Lakhankumawat/LearnCPP#606]
### Description

I want to add doubly linked list since it's absent in the Linked list folder 

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rutika1823** [comment]
Please assign this to me. I want to work on this issue under GSSoC'22

**Comment by Hend123** [comment]
Please assign it to me under GSSOC22 . I want to work on this issue

**Comment by Shatakshi-Choudhary** [comment]
Hey there, I think I can solve this issue, I will be implementing traversal, deletion, reversal & various other operations. This will probably take 3-4 days. I am a GSSoC'22 Contributer. Please assign this issue to me.

**Comment by yehia12yasser** [comment]
\assign

**Comment by Mrjoy832** [comment]
> Hey @Mrjoy832 Can I self-assign this issue as this has been delayed for a very long time. I'd be grateful if you could allow me to complete this task under GSSoC22.

You have to take permission from issue...owner?? 
@joe09222 when You make PR on it...finish it within 3 days either it will unassigned to you

**Comment by Sukriti-m** [comment]
It's been 3 days. Can this issue be handed over to me?

**Comment by Mrjoy832** [comment]
> It's been 3 days. Can this issue be handed over to me?

@Sukriti-m , Work on it ..only if it's not exist on main repo...
