### ISSUE TITLE
Title Pivot in rotated sorted array

### ISSUE THREAD

**Issue by Akriti-007** [Lakhankumawat/LearnCPP#609]
### Description

I would like to add a program which finds pivot in a rotated sorted array.

I want to work on this issue under GSSOC'22.

### Domain

Data Structure

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Shivani416** [comment]
I would like to work upon this issue , could you assign it to me? @Akriti-007

**Comment by Akriti-007** [comment]
ok I shouldn't work on this issue now
