### ISSUE TITLE
Strongly Connected Components (Domino)

### ISSUE THREAD

**Issue by deepu0201** [Lakhankumawat/LearnCPP#61]
### Description

This is a very demanding yet interesting approach of solving islands of nodes known as SCC, using the approach I used to learn.

@Lakhankumawat Please assign this issue to me, I am a GSSOC'22 contributor.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Please join meet today more details will be shared there

**Comment by deepu0201** [comment]
Is this issue considered as #GSSOC'22  contribution??

**Comment by deepu0201** [comment]
Since domino is a application based, so this will be acting as an example to explain the algorithm and what is the time complexity and how SCC algorithm works. @Lakhankumawat

**Comment by deepu0201** [comment]
@miraj0507  please assign me this issue.

**Comment by miraj0507** [comment]
Hello, So you can't just say strongly connected components, you need to mention weather it's Kosaraju,s algorithm or something else in the title. Do update it soon

**Comment by deepu0201** [comment]
@miraj0507 its kosaraju's algo

**Comment by deepu0201** [comment]
@miraj0507 please assign this algo to me.

**Comment by miraj0507** [comment]
Kindly update the title to Kosaraju algorithm
