### ISSUE TITLE
Arrays in C++

### ISSUE THREAD

**Issue by anveshajain19** [Lakhankumawat/LearnCPP#62]
### Description

An array is a collection of elements of the same type placed in contiguous memory locations that can be individually referenced by using an index to a unique identifier. 
I would like to contribute to this project.
Hello @Lakhankumawat, I am a GSSOC'22 contributor. I am eager to contribute, please consider the issue and assign me to this project. 
Thank you.

### Domain

CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by n4i9kita** [comment]
@anveshajain19 please be more specific, what would you like to contribute?
What are you planning to implement in array?
Or you want to write readme for it?

**Comment by anveshajain19** [comment]
@n4i9kita I am planning for some topics which you can put in the read me section like:
Standard Problems 
Factorial of large numbers 
Subarrays
Median Sorted Arrays
Circular array problems and much more.

**Comment by n4i9kita** [comment]
@anveshajain19 I think a better way to go about this would be to pick one topic (let's say Factorial of large numbers), add it's code with proper comment; and create an issue for each one separately. This way, others can also work on some other problem on arrays as well. 

@everyone : Mention the problem(or whatever you wish to implement) in the issue properly, and not just the data structure's name that you'd be working with. Better be, mention why the algorithm that you are implementing is better than the other ones out there to solve the problem.

**Comment by anveshajain19** [comment]
okay
I will make standard problems on Arrays so that others can also contribute in it.

**Comment by n4i9kita** [comment]
Let's join the meet. I think @Lakhankumawat  will clear it properly.

**Comment by anveshajain19** [comment]
okay

**Comment by n4i9kita** [comment]
Either we can close this issue, and you can create a new issue with the particular problem/ algorithm you are going to work on. Mention the time complexity of your approach, and maybe compare it to other approaches that are already there to solve it. Like, you can create an issue on "Median on sorted array". Do go through the contributing guidelines as well.

**Comment by anveshajain19** [comment]
Okay,  I will create a new issue with the particular problem/ algorithm I am going to work on.
