### ISSUE TITLE
Circular Linked List 

### ISSUE THREAD

**Issue by eshaan5** [Lakhankumawat/LearnCPP#620]
### Description

There is no code for the implementation of circular linked list. I would like to add the same including creation, insertion & deletion.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by eshaan5** [comment]
Kindly assign the same to me.

**Comment by Hend123** [comment]
Hello,
Please I want to work on this task

**Comment by eshaan5** [comment]
@Hend123 It's already there. I created this issue by mistake.

**Comment by Hend123** [comment]
@eshaan5 OK thanks
