### ISSUE TITLE
QuickSort on Doubly Linked List

### ISSUE THREAD

**Issue by nickel-28** [Lakhankumawat/LearnCPP#631]
### Description

Implementation of **quick sort** on doubly linked list

### Domain

Data Structure

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miretteamin** [comment]
Hii!
I am a participant in GSSOC'22. Can you please assign me this issue.
I've implemented a lot of algorithms and participated in many competitions.
Thank You.

**Comment by Shatakshi-Choudhary** [comment]
Hey, @n4i9kita I want to work on this issue. I will be implementing the Quicksort algorithm in a doubly linked list by partitioning the elements & sorting them recursively. I am a GSSoc'22 contributer . Please assign this issue to me. I will give my best.
