### ISSUE TITLE
Merge K sorted array (HEAP) (Priority queue)

### ISSUE THREAD

**Issue by rashita79** [Lakhankumawat/LearnCPP#646]
### Description

Algorithm for merging k sorted array using heap

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miretteamin** [comment]
Hii!
I am a participant in GSSOC'22. Can you please assign me this issue.
I've implemented a lot of algorithms and participated in many competitions.
Thank You.
