### ISSUE TITLE
Boundary traversal of tree 

### ISSUE THREAD

**Issue by rashita79** [Lakhankumawat/LearnCPP#647]
### Description

code for boundary traversal of tree

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Shivani416** [comment]
Hi ! I woruld like to work on this issue , could you please assign it to me ? @rashita79

**Comment by yehia12yasser** [comment]
\assign
