### ISSUE TITLE
All 4 views of tree (top,bottom,left,right)

### ISSUE THREAD

**Issue by rashita79** [Lakhankumawat/LearnCPP#648]
### Description

All views of binary tree left ,right using level order and top bottom using vertical traversal

### Domain

Data Structure

### Type of Contribution

Addition, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Shivani416** [comment]
I would like to work on this issue, @rashita79 could u assign it to me?
