### ISSUE TITLE
Array

### ISSUE THREAD

**Issue by TasmiyaSarfarazk** [Lakhankumawat/LearnCPP#672]
### Description

Finding Minimum and Maximum in an Array

### Domain

Data Structure

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Hend123** [comment]
Please assign issue to me

**Comment by Hend123** [comment]
\assign

**Comment by TasmiyaSarfarazk** [comment]
\assign
