### ISSUE TITLE
Static implementation of Queue 

### ISSUE THREAD

**Issue by janhavikale06** [Lakhankumawat/LearnCPP#674]
### Description

A queue is a dynamic data structure which consists a collection of elements that are placed sequentially one after another. The queue works according to the FIFO principle (First In First Out). Queue deletes an element from the top of the queue, ​but it adds an element at the bottom. We can represent queue by using linear arrays. There are two variables front and rear. Front and rear variables point to the position from where insertions and deletions are performed in a queue. Initially, the value of front is set to 0 and rear is set to -1. In this we are using empty() and full() to check whether the queue is empty or full.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by janhavikale06** [comment]
\assign

**Comment by juberiya1ajaz** [comment]
Please assign this to me. I want to work on this issue under GSSoC'22
