### ISSUE TITLE
Stock Buy And Sell

### ISSUE THREAD

**Issue by PrashantVIT1** [Lakhankumawat/LearnCPP#70]
### Description

Stock Buy And Sell
Problem Statement: You are given an array of prices where prices[i] is the price of a given stock on an ith day.

You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.

Examples:

Example 1:

Input: prices = [7,1,5,3,6,4]

Output: 5

Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.

Note: That buying on day 2 and selling on day 1 is not allowed because you must buy before you sell.

Example 2:

Input: prices = [7,6,4,3,1]

Output: 0

Explanation: In this case, no transactions are done and the max profit = 0.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by PrashantVIT1** [comment]
Hii I am a GSSoC'22 participant

**Comment by Lakhankumawat** [comment]
hi @PrashantVIT1  thanks for reaching me out but problem statements are not accepted in this project as GSSOC'22 contribution cause anyone you know can copy a problem from leetcode , paste solution in PR and can create such PR's which won't be a valid contribution , you can see what are the issues in the accepted issues , they have a algorithm dedicated , so i recommend you come up with something else .

Happy Coding !!

**Comment by Lakhankumawat** [comment]
you can contribute  this issue to the repo if you want to but it won't be counted in your point for GSSOC'22 but i recommend you contribute this issue instead of closing because you'll learn from it.

**Comment by PrashantVIT1** [comment]
Ok Sure I will add solution

**Comment by PrashantVIT1** [comment]
Ok, will try to complete this by today.
Thanks for reminder

**Comment by PrashantVIT1** [comment]
I want to close this issue as there is no response on pull request that I had created. Kindly look into this otherwise I will have to close it.

**Comment by PrashantVIT1** [comment]
Everything has already been done just few minimal conflicting changes are remaining
