### ISSUE TITLE
calculate the slope between two points in cpp

### ISSUE THREAD

**Issue by mahmoud21d** [Lakhankumawat/LearnCPP#705]
### Description

I am beginner And  I want to calculate the slope between two points .

### Domain

CPP

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by mostafa0adel** [comment]
bro can u assign it to me i am solve this problem

**Comment by mahmoud21d** [comment]
> bro can u assign it to me i am solve this problem

ok solve it

**Comment by mostafa0adel** [comment]
![ScreenShot_20220323192615](https://user-images.githubusercontent.com/101878363/159760451-7749860a-df51-4613-b356-b5e2e1ee0e3b.jpeg)
