### ISSUE TITLE
make a calculator with c++

### ISSUE THREAD

**Issue by ShahdMostafa30** [Lakhankumawat/LearnCPP#713]
### Description

Description

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by maryamosama33** [comment]
\assign

**Comment by FAR3OOON** [comment]
\assign

**Comment by Lakhankumawat** [comment]
issue assigned to @ShahdMostafa30  you can start working on this issue buddy
