### ISSUE TITLE
find the max and min number from three integer 

### ISSUE THREAD

**Issue by ShahdMostafa30** [Lakhankumawat/LearnCPP#714]
### Description

Description

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by mohamedreyad44** [comment]
\assign
