### ISSUE TITLE
asdasd

### ISSUE THREAD

**Issue by alyhosssam123** [Lakhankumawat/LearnCPP#718]
### Description

Descriptions

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by aymanantar** [comment]
as
