### ISSUE TITLE
Flatten a binary tree into linked list

### ISSUE THREAD

**Issue by abhi1e9-1e10** [Lakhankumawat/LearnCPP#72]
### Description

1. Recursively flatten the left and right subtree.

2. Store the left tail and right tail i.e.t he last elements of left and right subtree respectively.

3. Store right subtree in temporary variable and make the left subtree as right subtree.

4. Join right subtree with left tail.

5. Return the right tail recursively.

### Domain

Data Structure

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by ringo476** [comment]
Hi sir I want to add the explanation as well as the clean code for this algorithm.
please assign me this issue..
I'm a GSsoC'2022 participant as well.

**Comment by Lakhankumawat** [comment]
Sorry @ringo476  FCFS- First Come First Serve . This issue will be assigned to @abhi1e9-1e10
