### ISSUE TITLE
Intial bet

### ISSUE THREAD

**Issue by zaghloul128** [Lakhankumawat/LearnCPP#721]
There are five people playing a game called "Generosity". Each person gives some non-zero number of coins b as an initial bet. After all players make their bets of b coins, the following operation is repeated for several times: a coin is passed from one player to some other player.

Your task is to write a program that can, given the number of coins each player has at the end of the game, determine the size b of the initial bet or find out that such outcome of the game cannot be obtained for any positive number of coins b in the initial bet.

**Comment by Alitarek517** [comment]
you can just take the sum and if the sum%5==0 (becareful of the Special Cases )

**Comment by zaghloul128** [comment]
Thanks You Saved Alot of Time to me
