### ISSUE TITLE
Gift Wrapping Algorithm

### ISSUE THREAD

**Issue by helix17** [Lakhankumawat/LearnCPP#73]
### Description

Gift Wrapping Algorithm is used to find the convex hull (smallest convex polygon that covers set of points) of a given set of points. In this algorithm, the leftmost point is taken and then the next point to be connected to the hull is chosen if all the points are to the right of the line formed by joining the previous and the chosen point. This point is found in O(n) time complexity. This algorithm has a complexity of O(nm), where n is the number of given points and m is the number of points on the convex hull. 

@Lakhankumawat I'm a GSSoC 2022 participant. Please assign this issue to me.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by helix17** [comment]
@Lakhankumawat Can assign this issue to me. Thank You.

**Comment by Poojaamangal** [comment]
please have look at this @iamgunjan

**Comment by abdohamor** [comment]
assign to me

**Comment by Diishasing** [comment]
hi @Lakhankumawat please assign it to me
