### ISSUE TITLE
Skip Lists Implementation 

### ISSUE THREAD

**Issue by miretteamin** [Lakhankumawat/LearnCPP#732]
### Description

I want to add the implementation of Skip List

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by HagerRagaee** [comment]
cin>>x;
if(x=="skip")
{
 continue;
}

**Comment by miretteamin** [comment]
@Lakhankumawat I want this issue to be assigned for me.
Thank you!
