### ISSUE TITLE
Red-Black Tree

### ISSUE THREAD

**Issue by miretteamin** [Lakhankumawat/LearnCPP#733]
### Description

Description
Add Red-Black Tree implementation

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miretteamin** [comment]
@Lakhankumawat I want this issue to be assigned for me.
Thank you!

**Comment by Princeton21** [comment]
I would like to work on this issue. @Mrjoy832 @Lakhankumawat Kindly assign this to me.

**Comment by Mrjoy832** [comment]
> I would like to work on this issue. @Mrjoy832 @Lakhankumawat Kindly assign this to me.

@miretteamin as you have not created any PR on it..I am assigning it to @Princeton21  but @Princeton21 1st check if it's in main branch or not

**Comment by Princeton21** [comment]
Yes
