### ISSUE TITLE
[ADD] Kadanes Algorithm 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Lakhankumawat/LearnCPP#75]
Hii there , Greeting's of the day
Kadane's algo is one of the most important problem we face  and came across in the dynamic problem as well as in the greedy algorithm , ,,, 
.

The flow of the repository is : **LearnCpp/D-DynamicProgramming/**
Plss consider this algo as assign this to me ..
### GSSOC'22

Thank's and regard's :crossed_fingers:

**Comment by tingtong713145** [comment]
hello there ,                                                                                                                                                                                               Kadane's algorithm work like a 1-d problem in dynamic programming for finding maximum subarray sum in an array where the general approach is to set two variables current sum and max sum and we neglect the element contributing to negative sum by setting the current sum to zero when it is less than zero. It is a very useful and important topic of dynamic programming.  @Lakhankumawat Please assign me this issue.                                                                                                                                   Priya Nandi                                                                                                                                                                                  GSSOC'22 participant                                                                                                                                                                Thanks and regards.
