### ISSUE TITLE
remainder program

### ISSUE THREAD

**Issue by FCAI00** [Lakhankumawat/LearnCPP#751]
### Description

a program that prints the remainder of two numbers the user puts in.

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Abdallah-Hreba** [comment]
`#include <iostream>
using namespace std;
int main(){
    int dividend;
    int divesor;
    int remainder;
    cout<<"enter the first number(divedend): "<<endl;
    cin>>dividend;
    cout<<"enter the second number(divesor): "<<endl;
    cin>>divesor;
    remainder = dividend % divesor;
    cout<<"the remainder is: "<<remainder;
    return 0;
}`
