### ISSUE TITLE
[ADD] Manacher's Algorithm For (Longest Palindromic Substring)

### ISSUE THREAD

**Issue by singhkunal01** [Lakhankumawat/LearnCPP#76]
### Description

Hey @Lakhankumawat sir I want to add the Explanation as well as the clean code for this Algorithm which is not raised by anyone till now.
Please assign this to me !!

- I'm a GSsoC'2022 participant as well.

###Thank You
### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by miraj0507** [comment]
Hope you have gone through the community guidelines, I am assigning you the same.Kindly add a detailed explanation of the algorithm. also it is for Longest common palindromic substring. do mention it.
Good job go for it

**Comment by miraj0507** [comment]
also make sure it comes under Dynamic programming folder
