### ISSUE TITLE
Rotate list (3 ways)

### ISSUE THREAD

**Issue by rashita79** [Lakhankumawat/LearnCPP#767]
### Description

rotating a linked list to left by k i.e k times

### Domain

Data Structure

### Type of Contribution

Addition, Refactoring, Enhancement, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rashita79** [comment]
Assign this to me please

**Comment by Lakhankumawat** [comment]
Duplicate
