### ISSUE TITLE
 [ADD] Implement two stacks in an array

### ISSUE THREAD

**Issue by abhi1e9-1e10** [Lakhankumawat/LearnCPP#77]
Create a data structure twoStacks that represents two stacks. Implementation of twoStacks should use only one array, i.e., both stacks should use the same array for storing elements.

**Describe the solution you'd like**
Method 1 (Divide the space in two halves) 

**Describe alternatives you've considered**
Method 2 (A space efficient implementation) 

**Additional context**

**Comment by TushitaParashar** [comment]
Hey! I want to add an explanation and code for this problem, please assign this to me.
I'm also a participant in GSsoC'22.

**Comment by Smriti123Shukla** [comment]
Good morning!! Please assign this task to me. I will write clean and efficient code by describing comments and also telling their complexity.
I am a participant in Gssoc'22.
