### ISSUE TITLE
max number

### ISSUE THREAD

**Issue by samirahmeddd** [Lakhankumawat/LearnCPP#776]
### Description

find max number between n numbers

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by RanaEssam03** [comment]
added the max num problem
