### ISSUE TITLE
Segmented Sieve Problem

### ISSUE THREAD

**Issue by deepu0201** [Lakhankumawat/LearnCPP#79]
### Description

In this problem you have to print all primes from given interval. As it is a range query problem, we will be using segment tree as the name suggests.
@Lakhankumawat please assign me this issue.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by ringo476** [comment]
Hi sir I want to add the explanation as well as the clean code for this algorithm.
@Lakhankumawat please assign me this issue..
I'm a GSsoC'2022.

**Comment by uhini0201** [comment]
@Lakhankumawat  I am waiting for you to assign me this issue.

**Comment by deepu0201** [comment]
@Lakhankumawat  i am waiting for you to assign me this issue.

**Comment by miraj0507** [comment]
> @Lakhankumawat i am waiting for you to assign me this issue.

Hello, make sure you give a good description while you write the code for it , it must come under M-MathematicalAlgorithms/
follow all the community guidelines,
Good job go for it

**Comment by uhini0201** [comment]
@miraj0507 @Lakhankumawat can I work on this issue???
