### ISSUE TITLE
Linked list

### ISSUE THREAD

**Issue by arsh-111** [Lakhankumawat/LearnCPP#80]
I would like to implement operation on singly linked list (insert at begin, insert at end, insert at specific position, delete from begin, delete from specific position, delete from end, traverse), Circular singly linked list (insert at begin, insert at end, insert at specific position, delete from begin, delete from specific position, delete from end, forward traverse, backward traverse). Please assign me with this issue. Thank you.

**Comment by DlVYANSH** [comment]
Please assign this to me. I am also contributing in gssoc'22

**Comment by miraj0507** [comment]
> Please assign this to me. I am also contributing in gssoc'22

Kindly create a new issue, we operate on first come first serve

**Comment by miraj0507** [comment]
> I would like to implement operation on singly linked list (insert at begin, insert at end, insert at specific position, delete from begin, delete from specific position, delete from end, traverse), Circular singly linked list (insert at begin, insert at end, insert at specific position, delete from begin, delete from specific position, delete from end, forward traverse, backward traverse). Please assign me with this issue. Thank you.

Kindly pick a topic , I wont be able to allow all of the abovementioned algorithms all at once

**Comment by arsh-111** [comment]
Topic : Singly linked list
operations : Insertion from beginning, Delete from beginning, traverse.
thank you.
