### ISSUE TITLE
sum of two numbers

### ISSUE THREAD

**Issue by kareemsakkary** [Lakhankumawat/LearnCPP#828]
### Description

taking two numbers and printing the sum of them 

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by HodaTouny** [comment]
\assign

**Comment by nadaamohhamed** [comment]
assign
