### ISSUE TITLE
subtraction of 2 numbers

### ISSUE THREAD

**Issue by nadaamohhamed** [Lakhankumawat/LearnCPP#829]
### Description

Description

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by kareemsakkary** [comment]
\assign
