### ISSUE TITLE
product of two numbers

### ISSUE THREAD

**Issue by kareemsakkary** [Lakhankumawat/LearnCPP#830]
### Description

get two numbers and print the product of them

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by nadaamohhamed** [comment]
assign

**Comment by nadaamohhamed** [comment]
\assign
