### ISSUE TITLE
sum of 6 numbers

### ISSUE THREAD

**Issue by nadaamohhamed** [Lakhankumawat/LearnCPP#831]
### Description

Add 6 numbers

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by AyaAshraf21** [comment]
//assign
