### ISSUE TITLE
Find max of three numbers

### ISSUE THREAD

**Issue by mena7akim** [Lakhankumawat/LearnCPP#850]
### Description

Write a C++ program to take input 3 numbers and find the max in them

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by shahdmohsen133** [comment]
ASSIGN
