### ISSUE TITLE
Check if it is a palindrome string

### ISSUE THREAD

**Issue by Ahmed-walid** [Lakhankumawat/LearnCPP#856]
### Description

Given a string check if it is a palindorme string. 

What is a palindrome string ?
A string is called a palindrome string if the reverse of that string is the same as the original string. For example, radar , level , etc. Similarly, a number that is equal to the reverse of that same number is called a palindrome number. For example, 3553, 12321, etc.

Motivation:
Palindrome string problem is very popular and has a lot of variations and implementations with different time complexities. Asked frequently by recruiters at interviews.
Is also a good knowledge to gain specially for beginners as it easy to grasp and implement.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by rutika1823** [comment]
Can u please assign this issue to me under GSSoC'22?
