### ISSUE TITLE
Average of 3 Integers

### ISSUE THREAD

**Issue by Abdullah1S1K** [Lakhankumawat/LearnCPP#860]
### Description

Develop a program to read 3 integers from user then print the average of them

### Domain

CPP

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Abdullah1S1K** [comment]
اللي تحتي فلاح

**Comment by Abdullah1S1K** [comment]
اللي تحتي فلاح

**Comment by khaledsa1ah** [comment]
#860
@Abdullah1S1K 

#include<iostream>
using namespace std;
int main() {
    int n1,n2,n3;
    cin >> n1 >> n2 >> n3;
    cout <<(n1+n2+n3)/2;
}

**Comment by DoaaAli11** [comment]
#860
[https://github.com/DoaaAli11/mathematics-problems/blob/main/the%20average%20of%203%20nums.cpp](url)

**Comment by DoaaAli11** [comment]
#860
https://github.com/DoaaAli11/mathematics-problems/blob/main/the%20average%20of%203%20nums.cpp

**Comment by mostafaelsawy11** [comment]
#860

#include <iostream>

int main() {
    double num1, num2, num3, avr;

    std::cout << "enter first number to get an average of three: ";
    std::cin >> num1;

    std::cout << "enter second number: ";
    std::cin >> num2;

    std::cout << "enter third number: ";
    std::cin >> num3;

    avr = (num1 + num2 + num3) / 3;
    std::cout << "\naverage is " << avr;
}

**Comment by mahmoudsakrr** [comment]
[github_issue.zip](https://github.com/Lakhankumawat/LearnCPP/files/8365416/github_issue.zip)
#860
Solved Average Finding Calculator issue.

**Comment by omnya122** [comment]
#860
#include<iostream>
using namespace std;
int main(){
    int n1,n2,n3,avr,sum;
    cout<<"Please enter 3 integers: "<<endl;
    cin>>n1>>n2>>n3;
    sum = n1+n2+n3;
    avr = sum/3;
    cout<<"The average = "<<avr;
}

**Comment by mahmoudazizorignal** [comment]
#860
#include <iostream>
using namespace std;
int main()
{
    int arr[3];
    cout << "ENTER 3 INTEGERS TO PRINT THE AVERAGE: ";
    for(int i = 0; i < 3; i++)
        cin >> arr[i];
    cout << (arr[0] + arr[1] + arr[2]) / 3 << endl;
    return 0;
}

**Comment by medo4426** [comment]
#860
#include <iostream>
using namespace std;
int main(){
int n1, n2, n3;
cout << "enter 3 int values to calc the average : \n" ;
cin >>n1>>n2>>n3;
cout << "average is : " <<(n1 + n2 + n3)/3;
}

**Comment by rawwanntarekk** [comment]
#860
#include <iostream>

using namespace std;

int main()
{

int first_num, second_num, third_num,sum;
cout << " please enter 3 numbers : \n" ;
cin >>first_num>>second_num>>third_num;
sum = first_num + second_num + third_num;
cout << "the average is : " << sum/3;

    return 0;
}

**Comment by AdhamAD02** [comment]
#860

[GitHub Average.zip](https://github.com/Lakhankumawat/LearnCPP/files/8371346/GitHub.Average.zip)
