### ISSUE TITLE
Find the middle element of Linked List

### ISSUE THREAD

**Issue by tanya-gupta25** [Lakhankumawat/LearnCPP#88]
### Description

I will add all the approaches to find the middle element of Linked List along with their Time & Space Complexity.

I want to work on this issue under GSSOC'22.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by tanya-gupta25** [comment]
I want to work on this issue under GSSOC'22.

**Comment by n4i9kita** [comment]
@tanya-gupta25, what all approaches? 
Please mention here too.

**Comment by tanya-gupta25** [comment]
@n4i9kita 2 pointer approach & one another method using counter.
