### ISSUE TITLE
Interval Scheduling example in Java C++ C Python

### ISSUE THREAD

**Issue by Jyo561** [Lakhankumawat/LearnCPP#89]
### Description

Description

### Domain

Algorithm

### Type of Contribution

GSSoC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
No description , no explanation , describe your problem , and contributions are accpted in c++ only .

**Comment by Jyo561** [comment]
So i will be implementing the Greedy Algos in C++. as most follow only pseudo code this might be a helpful collecting of libraries which will help newbies implement the code efficiently
