### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by shaaban500** [Lakhankumawat/LearnCPP#90]
### Description

I will rewrite a clean standard code for binary search on a popular containers such as arrays, vectors, sets.. etc and it's enhancement because the current code is abit confusing.
( ADDITION )
 I will ADD another standard code for "binary search the answer" problems with a standard example for it.
I will also explain time and space complexities in each case. 
I am a competitive programmer who had used binary search in many problems , assign it to me.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by n4i9kita** [comment]
What are the updates, @shaaban500 ?

**Comment by shaaban500** [comment]
Soon : )
It will be done today or at most tomorrow

**Comment by goyalsaksh** [comment]
Hello , I am a gssoc contributor. please assign this issue to me

**Comment by shaaban500** [comment]
Don't 
I will finish it in two days
I just have exams now
