### ISSUE TITLE
LIS Dynamic Programming 

### ISSUE THREAD

**Issue by shaaban500** [Lakhankumawat/LearnCPP#91]
### Description

I noticed that DP section contains only two patterns of DP popular problems.
I know more patterns which I have trained on and solved a lot like : 
- LIS ( Longest Increasing Subsequence(

I can write clean standard code for it and show time and space complexities with comments.
I will provide code with links to the standard problem.
I will provide more than one way to solve this problem.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
You can only pick one problem at a time not many , create a issuse for one at a time and we'll be happy to accept that .

**Comment by miraj0507** [comment]
Kindly just work on Longest Increasing Subsequence, and make sure you come up with O(n^2) as well as o(n) time complexity , failing to come up with o(n), I shall reduce the question level to level1.
all the best, Go for it
