### ISSUE TITLE
Summation from 1 to N

### ISSUE THREAD

**Issue by MikelAntonio0098** [Lakhankumawat/LearnCPP#919]
### Description

Given a number N. Print the summation of the numbers that are between 1 and N (inclusive).

`Example :`

> input : 3

> output: 6

`Example :`

> input : 10

> output: 55

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by abdulrahman1238** [comment]
problem #919
