### ISSUE TITLE
Average

### ISSUE THREAD

**Issue by MazenBakry** [Lakhankumawat/LearnCPP#927]
### Description

Cant get the average of 3 numbers

### Domain

CPP

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by omaryousef10** [comment]
\assign
