### ISSUE TITLE
Reverse a Linked List in CPP

### ISSUE THREAD

**Issue by ChetasShree** [Lakhankumawat/LearnCPP#93]
### Description

Hi
I am a contributor at GSSOC'22, and I would like to contribute in CPP this problem statement, I will even add explanation and time comp and space comp and test cases.
Can you please assign this issue to me?

Than you

### Domain

Data Structure

### Type of Contribution

Addition, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Smriti123Shukla** [comment]
Good morning !! Please assign me this issue. I will add comments describing it and also complexity of solution.
I am a participant in Gssoc'22.
I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.
