### ISSUE TITLE
Symmetry check

### ISSUE THREAD

**Issue by yyyyAAAAAAAA** [Lakhankumawat/LearnCPP#939]
### Description

you will give a input have  numbers and number from 2 digits 
check if the number Repeat until the end
print "Yes" if it is 
otherwise print "No"

EX:
input
20202020202020
20
output 
Yes

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Sa7afy** [comment]
//assign

**Comment by Sa7afy** [comment]
#939
[#939.zip](https://github.com/Lakhankumawat/LearnCPP/files/8370497/939.zip)
