### ISSUE TITLE
Delete A node in linked list CPP

### ISSUE THREAD

**Issue by ChetasShree** [Lakhankumawat/LearnCPP#94]
### Description

Hi
I am a contributor at GSSOC'22, and I would like to contribute in CPP this problem statement, I will even add explanation and time comp and space comp and test cases.
Can you please assign this issue to me?

### Domain

Data Structure

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by omkar806** [comment]
Description : 
Hi
I am a contributor at GSSOC'22, and I would like to contribute in CPP this problem statement . I will explain this code in simplest possible way and also will add all the details such as time and space complexity  and also will do this problem in 2 methods .

**Comment by miraj0507** [comment]
> Description : Hi I am a contributor at GSSOC'22, and I would like to contribute in CPP this problem statement . I will explain this code in simplest possible way and also will add all the details such as time and space complexity and also will do this problem in 2 methods .

We work on first come first serve method .
