### ISSUE TITLE
input problem

### ISSUE THREAD

**Issue by Darsh0111** [Lakhankumawat/LearnCPP#947]
### Description

i can't take any input that include a space while using cin

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Salma-Mamdoh** [comment]
`#include <iostream>
#include<string>

using namespace std;
int main()

{
    string message;
    cout << "please enter a message \n";
    getline(cin, message);
    
}

`

**Comment by Salma-Mamdoh** [comment]
#include <iostream>
#include<string>

using namespace std;
int main()

{
    string message;
    cout << "please enter a message \n";
    getline(cin, message);
    cout << (message);
}

**Comment by Salma-Mamdoh** [comment]
[#947.zip](https://github.com/Lakhankumawat/LearnCPP/files/8371404/947.zip)
