### ISSUE TITLE
Inheritance and its implementation

### ISSUE THREAD

**Issue by Ashkul23** [Lakhankumawat/LearnCPP#95]
### Description

Frequent use of code written once, it is reusability.
One superclass can be used for the number of subclasses in a hierarchy.
No changes to be done in all base classes; just do changes in parent class only.
Inheritance is used to generate more dominant objects.

### Domain

CPP

### Type of Contribution

Addition, Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
Okay , but also tell how would you implement it .

**Comment by Lakhankumawat** [comment]
Describe your problem statement , if it is valid we will accept your issue.
