### ISSUE TITLE
circle_or_square

### ISSUE THREAD

**Issue by yyyyAAAAAAAA** [Lakhankumawat/LearnCPP#952]
### Description

you are given two integers .. the first one is the radius of a circle... the second one is the area of a square .. print true if if the circumference of the circle is greater than the square's perimeter .. print false if the square's perimeter is greater than the circumference of the circle.

Examples
circle_or_square(16, 625) ➞ True

circle_or_square(5, 100) ➞ False

circle_or_square(8, 144) ➞ True
Notes
You can use Pi to 2 decimal places (3.14).
Circumference of a circle equals 2 * Pi * radius.
To find the perimeter of a square using its area, find the square root of area (to get side length) and multiply that by 4.

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Mohandmagdy** [comment]
/ assign

**Comment by Mohandmagdy** [comment]
#952

**Comment by Mohandmagdy** [comment]
[Circle or Square.zip](https://github.com/Lakhankumawat/LearnCPP/files/8371340/Circle.or.Square.zip)
