### ISSUE TITLE
Problems on Linked List Data Structure

### ISSUE THREAD

**Issue by Kranthi-Guribilli** [Lakhankumawat/LearnCPP#96]
### Description

Hello there! I'm a GSSOC'22 contributor.
Description of my issue:
I found that in 'P-Problem Statements & Solution' folder there are no problem statements on the linked list. So, I will add beginner-level problems along with their solution on Linked List.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by DlVYANSH** [comment]
Hi!
I am participating in gssoc'22.
I can also contribute in this issue. I will add various "good" linked list problems which I had solved till date with various approaches. I will provide proper description of the code plus time and space complexity of the code

**Comment by Kranthi-Guribilli** [comment]
> Hi! I am participating in gssoc'22. I can also contribute in this issue. I will add various "good" linked list problems which I had solved till date with various approaches. I will provide proper description of the code plus time and space complexity of the code

Yeah, me too looking forward to contributing to this issue. We both can do it once they assigned it.

**Comment by DlVYANSH** [comment]
Yeah sure

**Comment by Lakhankumawat** [comment]
A mentor will assigned to you guys shortly please have patience

**Comment by Kranthi-Guribilli** [comment]
> A mentor will assigned to you guys shortly please have patience

Ok!

**Comment by DlVYANSH** [comment]
okk

**Comment by miraj0507** [comment]
We are not accepting PR's on P-Problem Statement for now, kindly go through all other folders and find a scope to write the best possible algorithm.
