### ISSUE TITLE
Insert node at nth position of linked list

### ISSUE THREAD

**Issue by DlVYANSH** [Lakhankumawat/LearnCPP#97]
### Description

Head of the linked list is given, insert the node at nth position in the linked list and display the linked list. If less than n nodes present, print the message "Less than n nodes present in the linked list".

please assign this to me. I am participating in gssoc'22.
I will provide proper description of the code with time and space complexity with various approch

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Smriti123Shukla** [comment]
This uses easy approach. Please assign me this task. I am a participant in Gssoc'22.

I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by DlVYANSH** [comment]
@Lakhankumawat where would i have to add the problem statement? In pr description or in the description of issue itself by editing it?
