### ISSUE TITLE
Calculat the area of rectangel

### ISSUE THREAD

**Issue by Ayman17** [Lakhankumawat/LearnCPP#982]
### Description

Take width and length from the user and print the area of a rectangle

### Domain

CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by HebaAzouz** [comment]
#982
