### ISSUE TITLE
WaterMelon Codeforces

### ISSUE THREAD

**Issue by zaghloul128** [Lakhankumawat/LearnCPP#991]
### Description

One hot summer day Pete and his friend Billy decided to buy a watermelon. They chose the biggest and the ripest one, in their opinion. After that the watermelon was weighed, and the scales showed w kilos. They rushed home, dying of thirst, and decided to divide the berry, however they faced a hard problem.

Pete and Billy are great fans of even numbers, that's why they want to divide the watermelon in such a way that each of the two parts weighs even number of kilos, at the same time it is not obligatory that the parts are equal. The boys are extremely tired and want to start their meal as soon as possible, that's why you should help them and find out, if they can divide the watermelon in the way they want. For sure, each of them should get a part of positive weight.

i divide the input by 2 but still there's an logical error

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by seko300** [comment]
\assign

**Comment by seko300** [comment]
if the input ==2 then it is wrong because it will be 1

**Comment by Rishita489** [comment]
Hey I am a GSSOC'22 Contributor . Can you please assign this issue to me . I have send the PR solving this issue #1123 . You can review and merge it .
